import type { MemoirChapterContent } from "@/lib/memoirBlocks";

// Transcribed verbatim from leg/chapter_04.html (the package Ahmad approved).
const FOLDER = "buyahka-abrar/chapter-04";
const img = (n: string) => ({ publicId: `${FOLDER}/${n}`, resourceType: "image" as const });
const vid = (n: string) => ({ publicId: `${FOLDER}/${n}`, resourceType: "video" as const });

const chapter04: MemoirChapterContent = {
  number: 4,
  slug: "chapter-4",
  title: "November 10, 1989",
  soundtrack: {
    name: "Chapter 4 — Marriage Formation",
    tracks: [
      { media: vid("23_audio"), title: "Anita Baker — Sweet Love" },
      { media: vid("24_audio"), title: "Madonna — Crazy For You" },
    ],
  },
  blocks: [
    {
      type: "hero",
      book: "Buyahka and Abrar",
      chLabel: "Chapter Four",
      title: "November 10, 1989",
      em: "Love Forged in Fire",
      subtitle: "The wedding I attended. Her father blessed the marriage with his presence and prayers. The mehr was one thousand dollars — everything I had. We had nothing else to give each other but ourselves, and we gave it.",
      meta: "Part I — Inheriting",
    },
    {
      type: "poem",
      title: "In the still of the night",
      translit: "From the chapals fragments · on Hina",
      stanzas: [
        { lines: ["In the still of the night, in its peaceful bliss", "It's in the air tonight.", "Don't put your feet on the floor.", "Please, stay here for a while."] },
        { lines: ["Allow me to place the stars on your walkway.", "I'll light up my heart to brighten up your path."] },
        { lines: ["What's a night without the moon?", "It can't breathe without the moon.", "How do you think I sufficed."] },
      ],
    },
    {
      type: "prose",
      lines: [
        { kind: "opener", text: "Six years after the kid refused to attend Hina's first wedding, he attended her second. He was eighteen. She was twenty-two. Her father blessed the marriage with his presence and his prayers. The mehr was one thousand dollars — every dollar the kid had. We had nothing else to give each other — not money, not a settled future, not the approval of every person in the room. So we gave each other ourselves. And the angels, who had been keeping the record, wrote it down." },
        { kind: "drop-cap", text: "November 10, 1989. A Friday. Two days after my eighteenth birthday. The nikah was performed in the living room at 89 Franklin Road — in Khalid Beg's house, the same room where he had received me and turned me away two years earlier. The same armchair. The same room. He had not changed his furniture. He had changed his mind." },
        { kind: "plain", text: "I want to tell you why we were not at a masjid. The simple answer is that the side of the family running the nikah did not have one. The Beg family had spent their adult lives building Dar ul Islah and had lost the lawsuit two years before, in 1987. The building still stood — the dome and the minaret, visible from the turnpike, exactly as the men had voted in 1979. But the building was no longer the Begs' to use the way a family uses a masjid for its own daughter's wedding. They had lost the steering and, in the practical sense that families know about and outsiders do not, they had lost the building too. A new leadership had it. A new tone shaped what happened inside its walls. You did not bring your daughter's nikah into a building whose direction you no longer trusted." },
        { kind: "plain", text: "So Khalid Beg did what fathers do when the institutions fail them. He brought the nikah home. He cleared the living room. He arranged the chairs. He asked an imam who would come to come. The whole ceremony fit in the room where the family lived — where the daughters had grown up, where the conversations of thirty years had happened, where I had sat across from him at fifteen and at sixteen and at seventeen as he tried to figure out who I was and whether to let me near his daughter. By eighteen the question had answered itself, on his furniture, in his room." },
        { kind: "plain", text: "In our culture, the bride's side runs the nikah. The groom's side runs the walimah. The nikah belongs to the woman's family because the woman is the one who is moving, structurally and ritually, from one household to another. Her father walks her in. Her father gives her away. Her father's living room is the right room. That part of the day belonged to Khalid Beg, and he carried it." },
        { kind: "plain", text: "Of my own family, only my father came. Ikram Koshul came. My mother did not. Shagufta was angry. Some of the anger was for the marriage. Some of it was for the years I had not been her son. Some of it was for the years she did not know how to talk about. Whatever it was, she was not at the nikah. I noticed." },
        { kind: "plain", text: "I have written elsewhere that we were the first couple in the community that got married. I want to qualify that. We were not the first couple in the community to have a nikah. We were the first couple in the community where the bride and groom had each grown up inside the community as children of the founders — the first generation marrying back into itself. The aunties had watched us across thirty Fridays a year for a decade. The uncles had watched. We were the first homegrown wedding, and the community knew it whether they would admit the meaning of it or not." },
        { kind: "plain", text: "Not everyone in the community was happy. They were not. Some had stories about Hina they had carried since 1983. Some had stories about me they had carried since 1987. Some had taken sides during the splintering and could not look at my father's face without remembering. Weddings in this community were never just two people. The room was small and the family ran it, but the community knew, and the community had its opinions." },
      ],
    },
    {
      type: "fpImage",
      eyebrow: "November 10, 1989 · The Nikah",
      image: img("01_image"),
      alt: "Nikah portrait, November 10, 1989. Ahmad in turban and suit, Hina in white, with their two fathers.",
      caption: "The room had changed nothing. The furniture was the same. The armchair was the same. Two fathers in a single frame — the one who had refused, now standing with the one who had pressed. The nikah was performed where the refusal had been performed two years earlier. The room did not change. The men in it did.",
    },
    { type: "sectionCard", roman: "I", heading: "What I Promised", lede: "A nikah is a contract. It is also a promise made out loud, in front of God, before the witnesses you owe the rest of your life to." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "A nikah is a contract. The mehr is set, the wali consents, the bride consents three times, the witnesses sign. It is not a sacrament in the Catholic sense. It is a promise made out loud, in the language of property and rights, because the deen takes property and rights seriously and refuses to pretend that love is enough." },
        { kind: "plain", text: "My mehr to Hina was one thousand dollars." },
        { kind: "plain", text: "It was every dollar I had. I was eighteen. I had been working at the flower shop since February 1988, when I was sixteen, since the time she had first put me on the payroll because I had nowhere else to go. I had been saving in the way a kid saves — without a plan, without a wedding in view, just because saving was what you did when you had been homeless once and did not intend to be homeless again." },
        { kind: "plain", text: "By November 1989 the savings had reached thirty-nine hundred dollars. Twenty-five hundred went to the walimah. One thousand went to her as the mehr. Four hundred went to the honeymoon. That was every penny I had to my name. I gave it as it needed to be given, and the witnesses signed." },
        { kind: "plain", text: "I want her sons to read this and know exactly what their father gave their mother that afternoon. He gave her everything. Not a number large enough to mean security. A number small enough to mean this is the floor of who I am right now and I am giving you the whole floor. The kid had nothing else. He gave the nothing." },
        { kind: "plain", text: "Hina's first mehr, in 1983, had also been one thousand dollars. I have written about that license in the previous chapter. The license itself sits in the appendix of this book. I want you to look at the two pieces of paper next to each other and notice that they say the same number." },
        { kind: "plain", text: "One thousand dollars in 1983. One thousand dollars in 1989." },
        { kind: "plain", text: "Same number. Different meanings." },
        { kind: "plain", text: "In 1983, the man writing the number was twenty-seven years old. He had a profession. He had a family with money. The thousand dollars was what he and the men around him decided a sixteen-year-old girl was worth as a wife. They could have written more. They wrote one thousand. The number was a ceiling." },
        { kind: "plain", text: "In 1989, the man writing the number was eighteen. He had no profession, no family money to draw on. The thousand dollars was every dollar he had on earth. The number was not a ceiling. It was a floor with nothing under it." },
        { kind: "plain", text: "Same paper. Two different deals." },
        { kind: "plain", text: "The mehr was the form the thing took. The form mattered. The number mattered less than what the number was a proportion of." },
        { kind: "plain", text: "Years later, when we had something, I would put more on paper for her in other ways. I would buy her things. I would sign the lease at Teaneck Flower Shop. I would do what husbands do when the years bring resources. But the day of the wedding, the kid had a thousand dollars and a duffel bag of clothes from the previous chapter, and he gave her the thousand dollars and kept the duffel bag, and the witnesses signed." },
      ],
    },
    { type: "pullquote", lines: ["Like my chapals at the masjid,", "my heart has been stolen and forever gone.", "Like chapals at the masjid —", "heart gets stolen and forever gone."], src: "on the nikah · chapals fragment" },
    { type: "sectionCard", roman: "II", heading: "Pakiza Mohabbat", lede: "A clean love. There is a phrase for it in Urdu that English does not quite carry." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "There is a phrase in Urdu that I want here. The English does not carry it. Pakiza mohabbat. Clean love. Pure love. A love made of wudu. A love that you bring to God before you bring it to the beloved, because the beloved is a trust from God before she is anything else." },
        { kind: "plain", text: "Pakiza mohabbat karna chata hain. Tilawat-e-Qur'an bhi pardna chata hain. Aur aap ke saath ek umar guzarni chata hain." },
        { kind: "plain", text: "I want to love you cleanly. I want to also recite the Qur'an. And I want to spend a lifetime with you." },
        { kind: "plain", text: "Mera aik chota sa kam kar do. Ek nikahnama lekar khud ko mere naam kar do." },
        { kind: "plain", text: "Do this one small thing for me. Take a nikahnama and put yourself in my name. The Urdu is courtship language and contract language at once, the way Urdu often is. The same word for name carries the legal weight and the love song. The man asking is asking with both hands." },
        { kind: "plain", text: "I had been asking with both hands since I was twelve. The wedding was where the asking finally found the right room." },
      ],
    },
    { type: "pullquote", lines: ["What is salat without wudu?", "Pakiza mohabbat.", "Tilawat-e-Qur'an bhi pardna chata hain."], src: "on the nikah" },
    { type: "fpVideo", eyebrow: "From the videotape · The Nikah · 0:52", video: vid("02_video"), poster: img("03_image"), caption: "Hina at the nikah. The videotape we watched every anniversary." },
    { type: "fpVideo", eyebrow: "The Nikah · the shy angle · 0:24", video: vid("04_video"), poster: img("05_image"), caption: "The shy angle. Her face the moment the room turned." },
    { type: "fpVideo", eyebrow: "Nikah day, in the car · 1:40", video: vid("06_video"), poster: img("07_image"), caption: "In the car. The day moving through itself." },
    {
      type: "prose",
      lines: [{ kind: "plain", text: "The videotape was real. The eighteen-year-old kid had hired a videographer because he believed in records, and the angels and the videotape both did their work that day. Every anniversary, on the couch in the den, the same scenes played on the television and the two of them watched themselves at the beginning, every time still surprised at how thin he was and how she looked." }],
    },
    { type: "sectionCard", roman: "III", heading: "She Married a Kid", lede: "Her words. He is a kid. She said it more than once. It was the truest thing anyone said about either of us in 1989." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "She married a kid." },
        { kind: "plain", text: "Her words. He is a kid. She said it more than once. It was the truest thing anyone said about either of us in 1989. I was eighteen. I had nothing. No money, no degree, no plan, no parents under the same roof, no extended family willing to host the wedding, no in-laws willing to attend, no community willing to bless it." },
        { kind: "plain", text: "I had what I had at eleven. I had the Fame lyrics, sent in 1981 through Cris Caves. I had a glass heart with white stripes that she had been wearing for seven years. I had a refusal to attend her first wedding when I was twelve that nobody had noticed. I had a job at her old flower shop. I had a Camaro with T-tops." },
        { kind: "plain", text: "I had her younger brother saying to her, in some private moment I will never be able to reconstruct — I can only tell you about him. He won't hurt you. Other stuff I don't know." },
        { kind: "plain", text: "That was the recommendation. The whole recommendation. He won't hurt you." },
        { kind: "plain", text: "After what they had done to her, that was the only criterion that mattered." },
        { kind: "plain", text: "I want my sons to slow down on what I just wrote. Their uncle Karrar — the one who had been my friend at the castle since 1986, the one who had been standing with me the afternoon his sister got out of the car and the look-away happened in fall light — was the one who closed the loop on the marriage. Not by giving a blessing. By giving the smallest possible recommendation. He won't hurt you. Six words. The lowest possible bar, in the right room, at the right moment, said by the right person." },
        { kind: "plain", text: "The community that should have given a longer recommendation could not. The family that should have given a louder one would not. The father who had walked her down the aisle in 1983 was, by then, in his own grief about what he had done. The mother who had carried gallons of milk up four flights of stairs was loving but not deploying. Naila was apart. Zarrar was holding his own house. Amina was younger and being raised. The recommendation, what there was of it, came from the brother who had been Ahmad's friend at the castle in 1986. Six words. He won't hurt you. The whole recommendation." },
        { kind: "plain", text: "She took it. She took the kid. Against every logic — hers, her father's, her mother's, her community's, her own — she took the kid. She trusted her compass. She trusted her younger brother. The compass said: him. The brother said: him. The world had been telling her, since she was fifteen, what to do, and the world had been wrong every time. She had stopped trusting the world. She had started trusting the compass." },
        { kind: "plain", text: "The compass said me." },
        { kind: "plain", text: "I do not know how to honor that. I have spent forty years trying." },
      ],
    },
    { type: "pullquote", lines: ["I can only tell you about him.", "He won't hurt you.", "Other stuff I don't know."], src: "Karrar to Hina · the whole recommendation" },
    { type: "fpVideo", eyebrow: "The morning after · November 11, 1989 · 0:13", video: vid("08_video"), poster: img("09_image"), caption: "November 11, 1989. The morning after. Thirteen seconds outside in the daylight, the two of them married and not yet finished being surprised by it." },
    { type: "sectionCard", roman: "IV", heading: "The Walimah", lede: "In our culture the bride's side runs the nikah and the groom's side runs the walimah. I was the groom's side. I ran it on my own." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "In our culture the bride's side runs the nikah and the groom's side runs the walimah. The walimah is the public celebration the day after — the meal the new husband puts on for the community as the first act of his marriage. It is, structurally, the husband announcing himself to the world as a husband. It is supposed to be the groom's family carrying the weight." },
        { kind: "plain", text: "I did not have a family carrying the weight. I had a father who came to the nikah and a mother who did not. I had two older brothers and a younger sister and a household I had not lived in for two years. The groom's side, in the structural sense, was me. The kid was the groom's side." },
        { kind: "plain", text: "I ran the walimah on my own." },
        { kind: "plain", text: "Every dollar I had saved at the flower shop and at every job I had had since I was fifteen, I spent on the walimah. I rented a hall. I hired a caterer. I hired an MC. I got a sound system. I ordered a wedding cake. I put flowers on every table. I chose tablecloths. I picked out wedding favors. In Pakistani-Muslim weddings in Bergen County in 1989, no one was doing this. Walimas were food and a little speaking. The boy was doing a wedding the way he had seen weddings done in films and at the country clubs where he had worked the kitchen. He was doing it because he wanted Hina to have the wedding she should have had the first time and didn't." },
        { kind: "plain", text: "I hired a photographer. I hired a videographer. I paid them in full. I want you to read those two sentences and notice what they say. The kid had decided, at eighteen, that this day would be witnessed by professionals because the family witnesses were not all going to come, and because Hina deserved a record of being the bride at a wedding she actually wanted, and because the angels who keep the record are real but the videotape and the photographs are real too, and the eighteen-year-old kid running the walimah on his own believed in records." },
        { kind: "plain", text: "Every anniversary, for the rest of her life, we sat on the couch in the den and watched the videotape of the walimah together. We laughed at how thin I was. We marveled at how she looked. We said to each other, in the way long-married couples say things without quite saying them, look what we did. Look what we did." },
        { kind: "plain", text: "The pictures from that day are somewhere in the boxes of this house. The videotape too. By the time you read this book, in the version that goes to the family, those pictures will be in the appendix. The kid in them is barely recognizable to me now — thinner than any of my sons have ever been, in a suit he could not afford, standing next to a woman in a kameez she had chosen herself, smiling like a man who had pulled off a thing nobody had asked him to pull off." },
        { kind: "plain", text: "He had pulled it off. He had spent every dollar he had on the day his wife should have had the first time. The walimah was a receipt for the marriage that had not been allowed to happen six years before. He was eighteen and broke the next morning. He did not regret it." },
      ],
    },
    { type: "fpImage", eyebrow: "November 12, 1989 · Valima Day", image: img("10_image"), alt: "Valima Day formal portrait of Ahmad and Hina, November 12, 1989", caption: "The day the kid had paid for himself. Every dollar from the flower shop. Every dollar from every job since fifteen. Spent on a wedding day his wife should have had the first time and didn't. He was broke the next morning. He did not regret it." },
    { type: "fpImage", eyebrow: "November 12, 1989 · Father and daughter", image: img("11_image"), alt: "Hina with her father Khalid Beg, November 12, 1989", caption: "Khalid Beg and his daughter. The same man who had said no in 1987 and yes in 1989, who had brought the nikah home when the masjid was no longer a place a Beg daughter could marry, who carried the older form of the framework Hina would carry forward for the next thirty years. He is in this photograph. The book returns to him in Chapter Twelve." },
    { type: "fpVideo", eyebrow: "Valima Day · walking outdoors · 0:14", video: vid("12_video"), poster: img("13_image"), caption: "Walking out into the day. Fourteen seconds of two people who had just been declared married moving across a parking lot in their wedding clothes." },
    { type: "fpVideo", eyebrow: "From the videotape · the walimah · 0:48", video: vid("14_video"), poster: img("15_image"), caption: "Hina walking through the room. The wedding she had been waiting for, finally hers." },
    { type: "fpVideo", eyebrow: "Walimah cake cutting · 0:21", video: vid("16_video"), poster: img("17_image"), caption: "Twenty-one seconds. The cake. Their hands. The room." },
    { type: "fpImage", eyebrow: "Poconos, 1989", image: img("18_image"), alt: "Honeymoon close-up, Poconos, 1989", caption: "The Poconos. 1989. The first days of the marriage that would hold until May 25, 2019." },
    { type: "fpVideo", eyebrow: "The face the camera kept finding · indoors · 0:08", video: vid("19_video"), poster: img("20_image"), caption: "Indoors. Eyes down. Eight seconds the videographer caught when he stopped framing the room and just framed her face." },
    { type: "fpVideo", eyebrow: "The face the camera kept finding · outdoors · 0:08", video: vid("21_video"), poster: img("22_image"), caption: "Outdoors. Daylight. Eight seconds in the daylight. The look that made the marriage worth what it cost." },
    { type: "sectionCard", roman: "V", heading: "The Khabaa Letter", lede: "August 1991. Twenty-one months in. A man writes his wife a five-page letter from a hotel room and does not finish it the way the first four pages would have led you to expect." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "In August 1991, twenty-one months into the marriage, I wrote Hina a five-page letter from a Khabaa hotel room. I was twenty. We had a son who was eight months old. The letter was a long meditation on the marriage, on the deen, on the man I was trying to be, on the ways I was failing at it. The first four pages read like a young husband sermon — earnest, a little overwrought, full of references to the Prophet (peace be upon him) and his wives, full of resolutions about how I would do better. The kind of letter a young man writes to convince himself first and his wife second." },
        { kind: "plain", text: "The fifth page broke the frame." },
        { kind: "plain", text: "I will not paraphrase what page five says. I want it reproduced inside this book the way I wrote it that night, on hotel stationery, in handwriting that has not aged well. The four pages before it have to be there too — without them, the fifth page is just a fragment. With them, the fifth page is the moment a young man stopped writing the sermon and started telling the truth." },
      ],
    },
    {
      type: "artifactGrid",
      label: "Artifact · Reproduction",
      heading: "The Khabaa Letter, August 1991 — Pages 1–4",
      images: [
        { src: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811317/buyahka-abrar/drive-docs/1y5pqMovurIS2V-mCuIeeeqKS__V_2fk8.jpg", alt: "Khabaa Letter, page 1 of 5" },
        { src: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811264/buyahka-abrar/drive-docs/1L_kkqPedWX8aSCqT1GABcRq0bZ8AL3xe.jpg", alt: "Khabaa Letter, page 2 of 5" },
        { src: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811306/buyahka-abrar/drive-docs/1w8ypYcmjx2SE62-yOaAXqCS_u83MmuCq.jpg", alt: "Khabaa Letter, page 3 of 5" },
        { src: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811246/buyahka-abrar/drive-docs/1eLGww_jin1cfr_wFZ_UE3Kmk5JhGvIwg.jpg", alt: "Khabaa Letter, page 4 of 5" },
      ],
      caption: "Pages 1–4 read like a young husband sermon — earnest, overwrought, full of resolutions. The kind of letter a young man writes to convince himself first and his wife second. Then comes page 5.",
    },
    {
      type: "artifactCard",
      label: "Artifact · The Reveal",
      heading: "The Khabaa Letter, August 1991 — Page 5",
      imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811268/buyahka-abrar/drive-docs/1MCVmt4lPjAPmZDuGLOAWOT-zaD84Odci.jpg",
      alt: "Khabaa Letter, page 5 of 5, the reveal page",
      caption: "Page 5 is the letter the young husband actually meant to write underneath the sermon — the line the first four pages had been working their way toward and could not say.",
    },
    { type: "sectionCard", roman: "—", heading: "Her Father's Letter", lede: "Late 1987 or 1988. From Khalid Beg to his daughter, who was by then twenty-one, divorced for over a year, living independently, sheltering a homeless sixteen-year-old." },
    {
      type: "prose",
      lines: [
        { kind: "plain", text: "I am breaking the chronology of the chapter for a minute, because I have to. Section III ended with Khalid Beg's house and what twelve years of his children's dispute over it did to Hina. I cannot leave Khalid Beg there. I have to put another piece of him on the page, because he is too large a man to be in this book only as a posthumous house, and because Hina kept this letter for thirty-one years, in her things, where I would find it after she died. She did not destroy it. She did not show it to me. She kept it. The keeping was a message. I am only now learning how to read it." },
        { kind: "plain", text: "My father-in-law, Dr. Khalid Beg, was a man I loved. I want that on the record before what comes next. He was the imam of our community. He was tall, gentle, intellectual, articulate, dignified, kind. He was the first imam at Dar ul Islah. He co-founded the masjid with my own father, Ikram, and five or six other families. He had walked into America with a PhD and a job as a research scientist, and he had walked out of academia into being a high school teacher in the Bronx because the masjid was a more important obligation to him than his own career. He was a saint to almost everyone who ever met him. And sometime in late 1987 or 1988, he sat down at a typewriter and wrote his twenty-one-year-old daughter a letter I am going to put on the page here, because the letter is what it is, and I am not going to paraphrase it." },
        { kind: "plain", text: "He had agreed to her living independently after the divorce. He says so in the letter. He calls it not very proper on my part. He says he sought Allah's protection and His forgiveness for both of us. He says Nusrat, her mother, had been against it from the start. He says he had thought Hina was mature enough to differentiate between right and wrong and that the independent apartment would let her recover from the emotional shock of what her first marriage had been. He had not, he writes, expected what came next." },
        { kind: "plain", text: "What came next was me." },
        { kind: "plain", text: "He names me by name. Abrar Koshal. He says I have given up my parents and my education and that Hina's behavior is helping me perpetuate the confrontation with my parents. He says her intentions, no matter how pure and how good, cannot be justified. He says he has personally advised her so many times. He says she has ignored him. He says he has come to learn that she even allows me to spend nights at her apartment. He says he wishes it was not true." },
        { kind: "plain", text: "Then he says what it is, in the language he carried: HARAAM. He says he cannot approve of it. He says if Hina and I are interested in developing a HALAAL relationship, this is certainly not the way of ISLAM. And then he says the sentence the letter exists to say:" },
      ],
    },
    { type: "quoteBlock", text: "In light of what I have said above I, in the name of ALLAH and His RASOOL command you both but you in particular to stop seeing each other in privacy with immediate effect. Immediately put a lock to your apartment with no one having access to that apartment including yourself without one or both of your parents. Move back to live with your parents and give a required notice of vacating to your land lord." },
    { type: "prose", lines: [{ kind: "plain", text: "And then the line I cannot read without putting the page down:" }] },
    { type: "quoteBlock", text: "Dear Hina, in case you decide to go against these clear instructions, that are in your own best interest, then I must declare that I shall have no father daughter relationship with you and Allah alone is enough to be my witness." },
    {
      type: "prose",
      lines: [
        { kind: "plain", text: "I shall have no father daughter relationship with you. The father who had walked his sixteen-year-old daughter into the wedding of August 1983. The father whose hand had signed the nikah papers with mehr of one thousand dollars to Yasin Qamaruddin. The father who knew about the beatings and the rape and had not stopped any of it. That father, four years later, was writing this daughter — who had survived all of it, returned home, divorced the man, taken a job, kept herself alive, given the homeless teenager from the masjid he himself had built a place to lay his head — and was telling her in the name of Allah and His Rasool that he would disown her if she did not put the boy out of her apartment." },
        { kind: "plain", text: "She ignored the letter. She kept the apartment. She kept the job at the flower store. She kept the door open. What I want to put down here is what was actually being exchanged between us in that apartment in 1987 and 1988, because the letter is the father's reading of it and the father's reading was the wrong reading. She was giving me a place to lay my head. I was giving her something of decency, of purpose, a reminder of more innocent times — the kid from the masjid she had grown up at, untainted, still recognizable as the boy he had been before everything. We were each what the other needed at the temperature the other could receive. The frame the father put on it — HARAAM, illicit, hidden — was not what was in the room. What was in the room was two people who had survived the same community and were holding each other up in a way the community had not done for either of us. We had asked the halaal route. I asked for her hand in marriage when I was sixteen. I was refused. We did try. Some things get buried because they have to get buried in order for you to keep walking." },
        { kind: "plain", text: "Hina had told me, back then, that her father had written and perhaps even shared the letter with her at the time. I knew. And then I did not know. The mind does what the mind has to do to keep moving through a life. You bury the things that would stop you if you looked at them straight. Thirty-one years later, after she had passed, the letter resurfaced in her papers and brought all of it back. The keeping of it for thirty-one years was its own message. She had not destroyed it. She had not waved it at me in any of our hard moments to say look what my father wrote. She had kept it where it would be found when neither of us could be hurt by it anymore. By the time I read it again, the man who wrote it had been dead for sixteen years, and the woman who had ignored it had been dead for months. The only person it could still reach was me, in my office, at the desk where I am writing this." },
        { kind: "plain", text: "And one year or two after he wrote it — November 10, 1989 — the same Khalid Beg walked the same Hina down the aisle to marry the same Abrar Koshul in his own living room. The mehr was one thousand dollars. He officiated himself. He signed his name as Imam on the nikahnama. I have written about that wedding in Chapter Four." },
        { kind: "plain", text: "Whatever I did between the writing of that letter and the writing of that nikahnama, I did in that window. I do not fully know what changed in him. I know what I tried to do. I know that by 1989 he had agreed to give me his daughter. I know that the agreeing was not a small thing for a man who had written what he had written. I know that he carried the letter and I carry it now and the gap between the two is one of the things I have spent forty years trying to understand." },
        { kind: "plain", text: "I loved him. I love him still. He was my father-in-law and the imam of the community I grew up in and the man whose daughter became my wife and the mother of my children. And he wrote this letter. Both things are true. The book holds them both at once." },
        { kind: "plain", text: "And I want to say one more thing here, because the children reading this need to hear it. The man who wrote that letter was practicing the law as he understood it. He believed he was obligated to write it. He believed Allah and His Rasool were watching him write it. He was wrong about what the law required of him in that hour, and the wrongness cost his daughter a piece of her father at a time when she had already paid for almost everything else with pieces of herself — but he was not wrong because he was a bad man. He was wrong because the law as he had received it had a gap in it, and the gap was exactly the shape of his own daughter. The law could disown a woman for sheltering a homeless boy. The law could not name what had been done to her four years earlier, in a basement, in South Carolina, in Durham, by a man it had walked her into at sixteen. The law had teeth for the symptom and no eyes for the cause. He was operating that law in good faith. His daughter was the cost." },
        { kind: "plain", text: "That is what the book is about. Not him. Not me. The gap between what the law required of him and what the law did not require of him. The first he saw and acted on. The second he could not see, because no one in the room he was standing in could see it either. The seeing was Hina's. The seeing was the twelve-year-old's at the wedding refusal. The seeing was almost no one else's. The law, as it was being lived, was producing victims at exactly the rate the law's blind spots predicted. He was a good man inside a system that had a hole shaped like his daughter. He wrote her this letter. She kept it for thirty-one years. He walked her down the aisle a year later. All of that, at once, is what one man inside that system could be." },
      ],
    },
    { type: "sectionCard", roman: "VI", heading: "The Castle, Fall 1986", lede: "The first time I saw her after the three years. Outside Teaneck High School, in fall light. I smiled. I looked away. She looked away. Neither of us said any of it out loud. Neither of us said it out loud for the next thirty-three years." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "Fall 1986. The castle. That is what we called Teaneck High School — two flights of stone steps up to the front, two stone towers on either side, an alcove under the steps you could stand inside out of the wind. Brisk air. Jacket weather. Leaves on the ground. The kind of fall afternoon where the light goes amber early and the whole campus turns the color of a photograph somebody took twenty years ago." },
        { kind: "plain", text: "Karrar and I were both students at the castle. Karrar was Hina's younger brother — younger than her by three and a half years — and a year older than me. June 27, 1970. He was a friend. Hina had come to pick him up or to drop something off — I do not remember the errand. What I remember is that he and I were standing somewhere near the front of the school and her car pulled up, and Karrar said something, and I went down with him to meet her." },
        { kind: "plain", text: "I had not seen her in three years. The last time I had laid eyes on her was the summer of 1983, before the wedding I refused to attend. She had been sixteen then. She was nineteen now, going on twenty. She had been gone the whole intervening time — Newark, South Carolina, Durham, Lima. She had come home to Franklin Road in November of 1985. By the fall of 1986 she had been working at the flower shop for about half a year and had retained the lawyer at Goldsmith Law Firm in September. The divorce was already in motion. The papers were being drafted while she was driving across town to pick up her brother from school." },
        { kind: "plain", text: "She got out of the car." },
        { kind: "plain", text: "I want to slow this down because the rest of this book sits on top of the next thirty seconds." },
        { kind: "plain", text: "What I saw was a face I had memorized at ten and not seen since I was twelve. The features were still there. The eyes were still hers. The way she held her shoulders was still hers. But the surface was not what it had been. She was heavier than she had been at sixteen. Her face was puffed in a way that does not come from food. The radiance — the particular thing about her that I had named to myself, at ten, as the most particular thing I had ever seen — the radiance was dimmer. The current had been turned down. Three years of being married to that man, in those cities, in that family's grip, had done what three years of that does. It was visible on her body. It was visible on her face. I could see it from across the parking lot before I was close enough to say salam." },
        { kind: "plain", text: "And here is the part I have not been able to write before now. I smiled when I saw her. You smile when you see someone you have not seen in three years. You are happy. You have been waiting. The little boy in you wants to run toward her the way little boys run toward people they have been missing." },
        { kind: "plain", text: "And at the same time my heart absorbed everything I was seeing on the surface of her. The heart is a second brain. It does its own kind of reading at its own speed and the reading does not wait for the smile to finish. By the time the smile reached my face, the heart had already taken in the puffiness and the heaviness and the dimming of the current and the gone radiance, and it had filed all of it for later, and once the heart files something it does not let it leave." },
        { kind: "plain", text: "I was happy and not happy in the same chest at the same instant. I was fifteen. I did not have the vocabulary for what was happening inside me. The vocabulary came later. The experience was already complete." },
        { kind: "plain", text: "What I felt, underneath the smile, was a layered shame. Shame for her family, for the people who had done this to her and let it be done. Shame for my own family, who had attended the 1983 wedding I had refused to attend, and who had been on the wrong side of the seeing then and were still on the wrong side of the seeing now. Shame for the community at Dar ul Islah, which had presided over the giving-away and had not stood up. Shame for the world, for being a place where this could happen to a girl of sixteen in 1983 in New Jersey and nobody in any of the rooms she walked through had been able to stop it." },
        { kind: "plain", text: "And shame for myself. The deepest layer. At twelve I had sat on the grass at the edge of an empty soccer field and refused to attend the wedding. That was the one act of my childhood I have been proud of my whole life. But the refusal had been silent. The refusal had not changed anything. The wedding had happened. The three years had happened. The thing in front of me — the woman who had gotten out of the car — was what my silent refusal had not been able to prevent. The shame was that I had seen, at twelve, what was about to be done to her, and I had been a child, and a child's seeing was not enough to stop it. The shame was for the limit of the child. The shame was also, in some quieter way, for being on this side of the parking lot able to look at her, when she was the one who had carried the actual cost." },
        { kind: "plain", text: "We looked at each other. I looked away. She knew I had looked away. She looked away. I knew she had looked away. She knew I knew." },
        { kind: "plain", text: "Neither of us said any of this out loud. Neither of us said it out loud for the next thirty-three years." },
        { kind: "plain", text: "She felt the shame too. Not for herself. For me, for letting me see it. For her brother standing somewhere near us not registering any of it. For the moment, for what it was forcing each of us to take in at once. She was a poet and a writer first and foremost. She paid that kind of attention to everything. She would have read the look-away the moment it happened. She would have read mine the way a poet reads a line. She would have known what was inside it. She would have looked away to give me the room she could not give herself." },
        { kind: "plain", text: "That afternoon, in front of the castle, in fall light, with Karrar standing somewhere near us not registering any of it, the language we would use for the rest of our lives was set. Not spoken language. The other one. The glance. The look-away. The knowing-without-saying. The two of us in a room together, for the next three decades, would communicate more in what we did not say than most couples communicate in everything they say. That language was set on a fall afternoon outside Teaneck High School in 1986. Neither of us authored it. The afternoon authored it. We both signed." },
        { kind: "plain", text: "I write about this again in another chapter, in another year of our marriage, when the half of the heart broke in 2018 and we held the broken half between us and looked at each other and did not say what we were not saying. The pattern was set in 1986. The pattern held until May of 2019." },
        { kind: "plain", text: "What did I do, that afternoon, after she had gotten out of the car and the look-away had happened? I do not remember. The afternoon ends there in memory. Whatever Karrar said next, whatever we did with the rest of that hour, the rest of that day, did not survive. The thirty seconds at the car survived. Everything else fell away." },
        { kind: "plain", text: "I am writing this in 2026. Forty years after the fall of 1986. The afternoon is still in my chest the way it was that afternoon. I do not know what to do with the fact that an afternoon outside a high school is still inside a man at fifty-four. I am going to leave it there. The chapter is not the place to resolve it. The chapter is the place to put it on the page." },
      ],
    },
    { type: "pullquote", lines: ["Neither of us said any of this out loud.", "Neither of us said it out loud for the next thirty-three years."], src: "on the language set that afternoon" },
    { type: "sectionCard", roman: "VII", heading: "What We Built in Each Other", lede: "She did not save me by being a saint. I did not save her by being a hero. We saved each other by being honest, in private, when nobody was watching." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "One of the things I have had to decide is how to talk about the marriage without lying. The lie that comes most easily is the one that says she saved me. The other lie that comes most easily is the one that says I saved her. Both are false." },
        { kind: "plain", text: "We built each other." },
        { kind: "plain", text: "Not metaphorically. Materially. She was the proof to me, when I was a child, that the dignified Muslim woman the Qur'an described actually walked around in the world — in a blue overcoat at the masjid, in the way she carried her body in a community that did not know what to do with her. I was the proof to her, when she was a young woman who had been broken and put back together, that the man the Qur'an described — the husband who is a garment to his wife, the man who is gentle with his women — was not a fairy tale. We were each other's evidence. Without that evidence, neither of us would have believed." },
        { kind: "plain", text: "She was the incubator of my critical thinking. I have written this elsewhere and I will write it again because it is true and the book has to carry it. What I saw happen to Hina between 1982 and 1986 made the seed my parents had planted in me — the small intuitions about right and wrong, the ten-year-old's questions on a burnt orange couch — germinate. Without her, the seed might have stayed a seed. The questions might have stayed questions. I might have become a comfortable man." },
        { kind: "plain", text: "I was — and this is the harder thing to say — one of the places she was able to stand for truth. The 1984 forced-abortion refusal poem. The \"Alone I have been\" letter. The 2014 letter that begins I cannot fight it alone. She was a writer her whole life, but the writing she did in our marriage was different from the writing she had done before. She had a witness. The witness made some things sayable that had not been sayable before." },
        { kind: "plain", text: "And then the shelter. In 1987 she gave me a foothold when I had none. She was twenty. She had no business saving anyone. She did it anyway. From 1989 forward I gave her structural shelter in return — the shelter of being a man in a world that listened differently to men. I do not romanticize that shelter. I did not earn it. The world handed it to me at birth because of my chromosomes and I handed it onward to her because she should not have needed it and the world had failed to see her without it. The shelter she gave me in 1987 was hers. The shelter I gave her was the world's, on loan." },
        { kind: "plain", text: "Goodness, decency, faith, love — these are not rankable. The marriage was not a transaction. I am not the hero of this book and Hina is not the hero of this book and the book has no hero, only witnesses, and the witnesses are us." },
      ],
    },
    {
      type: "asideCard",
      label: "A line that survived",
      heading: "From the chapals fragments · on Hina, on us",
      paragraphs: [
        "If a woman cries there can be many reasons. If a man cries there will only be one. A woman. We call it \"Love.\"",
        "You were so full of pride — I had to bring you to your knees.",
        "Smile every time we part — takin' a piece of my heart.",
        "I believe in love like I believe in God. You can't touch it, you can't see it, but you can feel the wrath and the awe.",
      ],
    },
    { type: "sectionCard", roman: "VIII", heading: "Who She Was", lede: "There is something I have to say about Hina that nobody else can say. I am going to say it the way I would say it out loud, to her sons, to her daughter, to the witnesses. I am going to say it once." },
    {
      type: "asideCard",
      label: "Spoken · first version",
      heading: "Hina",
      paragraphs: [
        "No one… I mean no one… is going to tell me who Hina was. No one. Because no one knew her. Not like I did. Not like I saw her. Maybe not even she fully knew herself.",
        "You have to understand — the life she had before I came along. The betrayal. The abuse. Married off at sixteen. Divorce. Her family — the people who should have protected her, who should have guided her — didn't. The community that preached love, faith, trust — they turned on her.",
        "She came back to Teaneck broken. Lost. Damaged. And she didn't tell anyone. She couldn't. Her morals, her pride, her ethics — she carried it all inside. She wasn't a chatterbox. She wasn't going to spill herself to people who had already failed her.",
        "And that's when I stepped in. I was there. Always. Watching. Caring. Always seeing her when no one else did. She fed off my courage. My stances. My way of standing in the world. And slowly she realized it. This is someone different. Someone extraordinary. Someone she could trust with her life, her heart.",
        "If her family — if anyone had really known her back then, they wouldn't have done what they did. But they didn't. They never did. And she wasn't going to share herself with them — not then, not ever. She was strong. Fierce. Ethical. Elegant. Private. Pure. Brilliant.",
        "Her love — for her father, for her younger siblings, for Allah (swt) and Rasulullah (saw) — unmatched. Her potential. Her smarts. Her dedication. Her purity. And yet she was broken. Lost.",
        "And together we found each other. Outcasts. Both of us. Battered by life, by the people who should have protected us. She needed purpose. She needed meaning. I needed purpose. I needed someone I could trust, someone who could see me. And we found it in each other.",
        "We became friends. Partners. Crutches. Anchors. Lovers. We worked together. We lived together. We fought the world together. And slowly, very slowly, we brought each other back to life.",
        "We saw each other raw. The work ethic. The struggles. The world outside. The people around us. And the intimacy — not just physical — mental, emotional, spiritual — no one can imagine that. We built a life. Honorably. Openly. Against all odds.",
        "And then our children came. Moaaz. Then the next. And our love, our resilience, forged them too. Part of the fire. Part of the life we built.",
        "Hina and I — no one else can understand this. Not the family. Not the community. Not the people who thought they knew her. They can't. Because the experiences that shaped her, that shaped me, that shaped us together — no one else lived them.",
        "We emerged from fire. Multiple times. Individually. Together. And that's why it's different. That's why our bond is extraordinary. That's why no one can tell you about Hina. Or about Abrar. Only we know. Only you can glimpse it through the life we built. Through what we shared. Through what we endured.",
        "This is who your parents are. And this — this is the truth.",
      ],
    },
    { type: "pullquote", lines: ["I took a sip of your chai.", "Ain't been right ever since."], src: "a fragment, on the marriage" },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "The walimah ended. The hall emptied out. The caterer packed up. The MC went home. Somewhere in the house at 89 Franklin Road, the chairs from the living room had already been put back where they had been the day before. The world did not change because two people had stood up in a living room and a kid had thrown them a wedding the next day on a flower-shop salary." },
        { kind: "plain", text: "But two people had stood up in front of an imam." },
        { kind: "plain", text: "The angels kept the record. The mehr was set at one thousand dollars — every dollar the kid had. Her father blessed the marriage with his presence and his prayers, and she stood at the front of the room and consented three times, the way the deen requires, in her own voice, as a woman of twenty-two who had already been broken once and put herself back together. I stood next to her and consented in mine. The witnesses signed. The contract was real." },
        { kind: "plain", text: "I would spend the next twenty-nine years and seven months trying to be worthy of the promise I made that afternoon. I would fail at it many times in many ways. I will tell you about the failures in the chapters that come. The marriage was not a smooth road. We emerged from fire multiple times, individually and together, and the fire was real and the emerging was real and neither was guaranteed." },
        { kind: "plain", text: "But the wedding was real. The mehr was real. The thing we said in front of the witnesses was real. And on May 25, 2019, when I closed her eyes for the last time, what I closed them on was the keeping — not the perfection of it, but the keeping. I had not left. She had not left. The contract had held all the way to the end. The angels had the record. They have it still." },
        { kind: "plain", text: "What I owe her now — what this book is, in its slow way — is the writing it down. Forty years late in some places. But written." },
      ],
    },
    {
      type: "artifactRow",
      rowLabel: "The Contract and the Doorbell",
      heading: "What is on paper, what is on the scan",
      items: [
        {
          imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811241/buyahka-abrar/drive-docs/1dL3zclCe4XVxFr_BK6xz8NT6EymuhWxX.png",
          alt: "Ahmad and Hina's nikahnama, November 10, 1989",
          caption: "The nikahnama. November 10, 1989. Bridegroom: Ahmad Abrar S. Koshal. Father: Muhammad Ikram Koshal. Wali (Guardian): Khalid Beg. Mehr: $100,000 — to be paid in full when demanded. One hundred times what Yasin Qamaruddin had agreed to pay. The damin (guarantor): M. Koshal. Bridegroom's signature: \"Abras Koshal\" — in his hand at eighteen.",
        },
        {
          imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811259/buyahka-abrar/drive-docs/1IvJvArQsB9hlnTw7hPDG6LEE9zGzsfhL.jpg",
          alt: "The Stetson, handwritten doorbell scene",
          caption: "\"The Stetson\" — Ahmad's handwritten draft of the doorbell scene. The first complete prose version, in his hand, of the moment the kiss was held back at the door of 89 Franklin Road.",
        },
        {
          imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811213/buyahka-abrar/drive-docs/13N-BUQVhBd0Y2Ieie3FWzT-3k4dWeLhG.jpg",
          alt: "A Simple Note, the Cris Caves 1981 letter-carrier scene, handwritten",
          caption: "\"A Simple Note.\" The 1981 letter-carrier scene in Ahmad's hand. Cris Caves on Alicia Avenue. The crystal heart pendant came back to him through the letter carrier — a chain that had not yet found its neck.",
        },
      ],
    },
    { type: "chapterEnd", nextTitle: "Chapter Five — The Flower Shop" },
  ],
};

export default chapter04;
