import type { MemoirChapterContent } from "@/lib/memoirBlocks";

// Transcribed verbatim from leg/chapter_08.html (the package Ahmad approved).
const FOLDER = "buyahka-abrar/chapter-08";
const img = (n: string) => ({ publicId: `${FOLDER}/${n}`, resourceType: "image" as const });
const vid = (n: string) => ({ publicId: `${FOLDER}/${n}`, resourceType: "video" as const });

const chapter08: MemoirChapterContent = {
  number: 8,
  slug: "chapter-8",
  title: "The Last Year",
  soundtrack: {
    name: "Chapter 8 — Final Week",
    tracks: [{ media: vid("05_audio"), title: "Arijit Singh — Baaton Ko Teri (sparse)" }],
  },
  blocks: [
    {
      type: "hero",
      book: "Buyahka and Abrar",
      chLabel: "Chapter Eight",
      title: "The Last Year",
      em: "May 25, 2019 · Ramadan 20, 1440",
      subtitle: "The glass heart broke in 2018. She had a year left. I did not know that. I think it knew.",
      meta: "Part III — Rupture & Collapse",
    },
    {
      type: "poem",
      title: "I Adore Her",
      translit: "A love forged in fire · raw, after",
      align: "left",
      stanzas: [
        { lines: ["I adore her", "A love forged in fire", "Every time i walked by her", "She called me her", "Rock of Gibraltar", "We never figured out who was whose anchor"] },
        { lines: ["Like Abu Bakr", "We did everything first", "We became history", "We are history"] },
        { lines: ["Still flow through my soul"] },
        { lines: ["I'm trying to leave because you wouldn't stay"] },
        { lines: ["You are getting on my last nerve"] },
        { lines: ["To hell with these people — How could they understand"] },
        { lines: ["Everyday the wind keeps whispering your name"] },
        { lines: ["Won't let me live nor can i die"] },
        { lines: ["I've been tryin to leave because you wouldn't stay"] },
        { lines: ["A love that ran that deep"] },
        { lines: ["How do i fight God over you — But i try"] },
        { lines: ["Why does this pain feel so good, its the only thing that lets me know that i am still alive"] },
        { lines: ["Like a shell like a cocoon I have this butterfly living inside of me"] },
        { lines: ["Did you really have to die in order to save my life"] },
        { lines: ["Did you really have to die in order to save our lives?"] },
        { lines: ["I cant make sense of any of it.."] },
        { lines: ["I dont understand why the birds still sing"] },
        { lines: ["You touch my skin like ocean rain"] },
        { lines: ["You came and went like the tide"] },
        { lines: ["Only you and I knew we were meant to be"] },
        { lines: ["I had you and you had me.."] },
        { lines: ["When the world turned its back on you — God sent me."] },
        { lines: ["When the world turned its back on me.. You became my deen. My peace."] },
        { lines: ["We never had to speak — glances and mental telepathy"] },
        { lines: ["I didn't realize that you had to die", "In order to save my life", "I didn't realize you had to die", "And leave me in solitude", "So i could see the truth", "So i could begin to remake myself and become worthy of you", "Once again pure and clean like my youth", "I still don't know who saved who?"] },
        { lines: ["I am wiser and smarter now..", "Our Joys and Pain — I cherish them so dearly — I cherish them the same."] },
        { lines: ["Our highs and Lows —"] },
        { lines: ["You never fought for me — You never would fight for me…"] },
        { lines: ["In order to preserve your dignity —"] },
        { lines: ["I fought the world and I fought God too"] },
        { lines: ["How did you see everything so clearly."] },
        { lines: ["35 years together but it seems you came and went like the tide"] },
      ],
    },
    { type: "sectionCard", roman: "I", heading: "The Glass Heart", lede: "Ramadan 1402 AH. The summer of 1981. I was nine. She was fourteen. I gave her a glass heart. She wore it through every worst time of her life. It broke in 2018. Half is still here." },
    {
      type: "prose",
      lines: [
        { kind: "opener", text: "The glass heart I gave Hina in Ramadan of 1981 broke in 2018. The same one. The one in Chapter One. The one she wore through her first marriage and her return and her second marriage and every year that followed. Glass that age does not just break. Not that kind of glass, not that kind of crystal, not the way it happened. Hina told me it had broken. I did not see it happen. She just told me. The half I still have is on my dresser. The other half is gone. I do not know where it ended up." },
        { kind: "drop-cap", text: "It is not believable, what I am writing. In Ramadan of 1981 a boy of nine gives a glass heart to a girl of fourteen. The girl carries it her entire life. Thirty-seven years later it breaks, one year before she does. If I had read it in someone else's book I would have thought they were embellishing. The glass heart is the proof. The half on my dresser is the proof. I am writing this with it in front of me." },
        { kind: "plain", text: "The ages matter. Hina was born January 1, 1967. I was born November 8, 1971. The gap between us was always four years, ten months, seven days — the same gap at every moment of our lives, never five years, never less. In Ramadan of 1981 I was nine years old. Hina was fourteen. By the end of the next year, 1982, the adults around her were already moving toward what would become her engagement at fifteen and her wedding in August of 1983. The boy giving the glass heart in Ramadan was nine years old, holding a small thing in his hand for a girl who, in the calendar window the boy was giving her the heart, was on the edge of being given away to a man twice her age." },
        { kind: "plain", text: "The heart was not about dating. It was not about boyfriend and girlfriend. It was not about anything that the world would later make it into. It was about innocence. The purity of a gesture made by a child of nine who saw something in a store and saw a teenager he had been put on the earth to know and bought the heart because the heart was what he had to give and what she was worth receiving. She kept it because she understood what it was. She wore it through her worst times — the August 1983 wedding, Lima in 1984, the forced abortion that November, the years in Durham, the return in November 1985, the rebuilding that began in 1986 — because the gesture had been pure and she was holding onto something pure in a world that had stopped being pure to her in the same months and the same years the boy of nine had been giving it to her in." },
        { kind: "plain", text: "The heart carried her. That is the only way to say it. The heart carried her through what nobody else could carry her through. It did the work the adults around her would not do." },
        { kind: "plain", text: "It broke in 2018. Not from a fall. Not from being struck. Glass like that, in a setting like that, does not break from ordinary wear. It broke anyway. The half stayed with her. The other half disappeared." },
        { kind: "plain", text: "Of course we had spoken about the heart over the years. Not in public. Not in front of the family. We sat quietly with what we knew. But between us — as a husband and wife who never stopped being infatuated with each other, in 1989 and in 1992 and in 1995 and in 2000 and in 2004 and in the years after — she would say things to me about the heart. She would say: Abrar, you couldn't imagine — how this heart necklace got me through the worst of times. And I would brush it off. I would not let her finish. Not because I did not want to hear it. Because I did. Because every time she said it I would feel the embarrassment and the shame — for knowing what I knew, and for having seen what no future husband should ever have had to see. I write about this elsewhere in this book under the words Look away. The Look-Away is its own thing. The heart-necklace conversations were a piece of it. The slow-hand fury, the embarrassment, the shame for having seen — those were running underneath the infatuation every time. Both registers at once. Always." },
        { kind: "plain", text: "So when she showed me the broken half in 2018, what passed between us was not silence. It was the same thing that had been passing between us for thirty years about the heart. I held the half in my palm and looked at her and she looked at me and we kept going. There was nothing new to say. The conversation we had been having about that heart since we were married had not finished. It was still going. It is still going now." },
        { kind: "plain", text: "One year later she was gone." },
        { kind: "plain", text: "The half is here." },
      ],
    },
    { type: "pullquote", lines: ["The glass heart is the proof.", "Without it the whole story sounds like a man exaggerating after the fact."], src: "Abrar · on the half that remains" },
    { type: "fpImage", eyebrow: "2018 · The year too much arrived at once", image: img("01_image"), alt: "The crystal heart pendant after it broke in 2018, one year before Hina passed", caption: "The heart broke in 2018, when the weight she had carried for thirty-five years finally arrived all at once. Half remains. Half went where she went." },
    { type: "sectionCard", roman: "II", heading: "The Last Year", lede: "2018 into early 2019. The Karrar and Amina fight bled through everything. Underneath it, the year I spent with my eldest son preparing for his wedding. Trips to Indiana. Eleven hours in the car alone with Hina. Some of the best time we had together." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "The last year of Hina's life was dominated by the Karrar and Amina fight. I have written about that fight in Chapter Seven. The fight had been between those two from the beginning — it did not narrow to them in 2018; it had always been them. By 2018 it was still them, with Hina sitting in the middle of it as the pseudo-mediator she had been made into for twelve years." },
        { kind: "plain", text: "The selfishness of the two of them deciding to surface, in 2018, what they had not dealt with for fifteen years — this was the doorway through which the big wound surfaced again. The Beg-family wound. The one she had been carrying since she was sixteen. It had reopened at the worst possible time." },
        { kind: "plain", text: "The mechanics need naming, and they are harder to name than they first appear. This is the natural phenomenon that happens in families when a parent passes and there is a house to be divided between siblings — only it is less mechanical than the word mechanics suggests. In 2006, when Auntie Beg passed, the five Beg siblings sat down to settle what had to be settled. The house at 89 Franklin Road. The inheritance. What they had to work from was not a formal document. There was no will that laid the matter out cleanly. What there was, instead, was memories of things their parents had said over the years, family dynamics that went back decades, family history, needs, logistics, the relative standing of each sibling inside the family. All of that came into play. And Hina, by the kind of unspoken default that families fall into, was treated as a sort of authority — without any formal authority being given to her. She was the middle child who had been raised inside the parents' household longest, the one her mother had come to when she wanted things settled before she died. The siblings looked to her. But the looking did not come with paperwork. Hina was holding the closure of a settlement that had not been formalized. She would write about all of this in her own hand, in notes I have, in the month before she went into the hospital. I will get to those notes." },
        { kind: "plain", text: "What the sit-down produced, in the end, was that the two younger ones — Karrar and Amina — got what they wanted. They got the house, between themselves. The three elder siblings — Naila, Zarrar, and Hina — did not get an equal share of the claim. Not by anyone being shoved aside. By the soft accumulation of all those factors. The way these things actually go when there is no document. I knew this was not their mother's wishes. But we had to move on." },
        { kind: "plain", text: "For a few years after that, Karrar and Amina were best friends. Chummy-chummy. A honeymoon period between the two who had consolidated the house. The two of them on one side of the family, the elders on the other side, the house their shared possession. That is how it stood. That is how it would have continued to stand if the chumminess had held." },
        { kind: "plain", text: "It did not hold. Cracks formed between them. Then Amina moved out. And the matter that had never been formally closed — that had been left settled-but-not-closed in 2006, on the soft-factors basis — was now exposed for what it was: a thing that had never had a real ending. There was nothing to point to. No signed paper. No clean line. Just the original sit-down and what had emerged from it and what had been understood between people, which is the most fragile kind of agreement there is. Without a piece of paper, the dispute followed her into her body." },
        { kind: "plain", text: "What happened next is the natural phenomenon also. When something is left unfinalized in a family, the asking-and-positioning does not end. It goes on. The whining started. The complaining. The propaganda. The choosing of sides. The getting of allies. Continuous sidebar conversations. Each of them looking for someone, in the family or outside it, who could handle the close they had never been able to handle themselves. Now both Karrar and Amina were trying to pull everyone in — friends, family, kids, anyone they could get to listen — because each of them needed an audience for the case against the other, and because the matter underneath both their cases was still genuinely unsettled. Twelve, thirteen years of this. Unable to settle it. Unable to stop reaching out to people about it." },
        { kind: "plain", text: "Hina was not the Sun. Hina was the Moon — reflective, gentle, worn down by personalities, by family, by community, by life in general. Materialistic things were not her focus. They never had been. She had been treated as the authority in 2006 without being given the authority, and now in 2018 she was being asked to carry the consequence of a matter she had never been empowered to actually close. The two who had taken the house in 2006 were now, twelve years on, dragging the sister who had been their informal authority into their fight over what should have been formally settled at the start. The chasm could not be wider between who Hina was and how they handled this." },
        { kind: "plain", text: "I want to say what twelve years of that does to a body. Cortisol does not negotiate. A body that is asked to hold, for twelve years, a property fight that is not hers to hold — while her household and her daughter and her business and the man she had married watch her hold it — runs out of what bodies have. She ran out. The body kept the score. The score was the heart that was hospitalized in November of 2018, and the valve that was the wrong material in May of 2019. The body wrote its own ledger. The ledger came due on its own schedule. The schedule did not consult the carrier." },
        { kind: "plain", text: "Let me tell you who Hina was. If Hina owed you three pennies she would chase you down again and again and again, to the point of exhaustion, until you would noticeably get aggravated — just to settle her three-cent debt. She did this with her husband. She did this with siblings, with strangers. It would drive me crazy. As God is my witness, I never asked her for a penny. And when I found out she was sliding money into our account, I was pissed. But that is who we were. That is who she was." },
        { kind: "plain", text: "In the same week the heart was being told something was wrong, I was at the keyboard at eleven-fifteen at night writing to Karrar. November 5, 2018. The letter was a brokering attempt. A proposal. A peace protocol. I named the medical side — matters of science and medicine, taking a proactive approach, engaging the doctors. I named the other side. Then there is the emotional/mindset issue. Both you and Amina have broken her heart, are breaking it. I told him, in writing, what was being done to his sister. I had not been able to say it at any family table. I said it at the keyboard at 11:15 p.m. because at that point the speaking had been exhausted." },
        { kind: "plain", text: "The next morning at eight-twelve I wrote to both of them. Karrar and Amina, the same letter. The ceasefire proposal. A conference call. Say salaam. Agree to be respectful and not touch on how things had been handled until your sister is recovered. Hang up the phone. I asked them for a temporary reconciliation for each of them and for Hina first and foremost. I was writing a peace protocol while my wife was failing." },
        { kind: "plain", text: "They did not take it." },
        { kind: "plain", text: "I want to say something about who I was writing to, in those two letters at those two hours. Karrar had been my friend since the castle. June 27, 1970. A year older than me. We had stood together at the front of Teaneck High School in 1986 and his sister had pulled up in her car and gotten out, and the look-away between her and me had happened with him standing somewhere near us not registering any of it. The Karrar of November 2018, receiving an eleven-fifteen p.m. letter from his brother-in-law about what was being done to his sister, was the same Karrar from the alcove of the castle thirty-two years earlier. The letter was not from a stranger. The letter was from a brother-in-law who had been a friend-in-law-before-being-a-brother-in-law for three and a half decades. The Karrar receiving it was the brother of the woman the letter was about and the friend of the man writing it. The letter still did not produce a return." },
        { kind: "plain", text: "My emails are there, after. Hina's handwritten notes are there. The lessons are there. We do not hate the people. The actions were atrocious." },
        { kind: "plain", text: "The look-away language Hina and I had been using since 1986 was the only language we had left for what was happening to her now. We did not say what we were not saying. We had thirty-two years of practice not saying things. The practice held. It also stopped working, because what was happening to her body in 2018 could not be held inside a glance. The glance had carried us a long way. By 2018 the glance was no longer enough. There was no language between us that was enough. I do not know if any couple has the language for what was about to come." },
        { kind: "plain", text: "And underneath that, alongside it, around it, was the other half of 2018, which I want to say plainly because it was beautiful. Most of 2018 was the year of my eldest son's wedding. Moaaz and Qurat-ul-ain had been introduced, had spoken, had decided there was real compatibility between them. The engagement took place in April of 2018. The wedding was set for November. From April through November there were trips back and forth to Indiana, where Qurat-ul-ain's family is. Wedding planning. Wedding stuff. The kind of months that are wonderful for a father and a mother in a way that is hard to describe to anyone who has not been in them." },
        { kind: "plain", text: "Hina and I drove together. Eleven hours each way. Just the two of us in the car. Sons, hear this: eleven hours alone in the car with their mother, sometimes twice in a week. Some of the best times we ever spent together were in 2018 in that car going to and from Indiana. The warmth was coming back into our marriage. Not back to the early years — you do not get back to the early years — but a different warmth, a warmth that thirty years of marriage builds when both people are aging into it together. We were going to come together as a family again. The eldest was getting married. The focus was returning to the household. The business expansion phase was ending. I was scaling back. We were about to enter the phase we had been waiting for since 1989." },
        { kind: "plain", text: "I put more into Moaaz's wedding than I had put into my own when I was eighteen. By God, I did. Alhamdulillah. I gave that wedding everything. Hina did the same. It was, for both of us, a magical year on that side of the calendar." },
        { kind: "plain", text: "On the other side of the calendar, Karrar and Amina were tearing into each other over Franklin Road, and the friction was bleeding into us, and the Beg-family wound was reopening, and Hina was being asked to hold both sides at once — the magical side of preparing her eldest son's wedding, and the worst side of being made the carrier for a fight her two younger siblings should have settled twelve years earlier. She held both. Nobody else could see her holding both. I could see her holding both. I could not take either weight off her. I tried. The trying did not lift it." },
        { kind: "plain", text: "This is the year. Magical on one side. Cracking on the other. Hina in the middle holding both. The glass heart breaks in the middle of it, sometime in 2018, and the conversation we had been having about that heart for thirty years keeps going, the way it always had." },
        { kind: "plain", text: "The bearing was about to exceed what her body and heart could hold. She was hospitalized in November of 2018 for the heart. She had a year left. I did not know that. I think it knew. The mercy of what came in May of 2019 was not legible to me as mercy at the time. It is legible now. I will say more about that in Chapter Twelve." },
      ],
    },
    {
      type: "asideCard",
      label: "A note · on a line I had written years before that came true in 2018",
      heading: "I would be your dreams — if I could be",
      paragraphs: [
        "Years before 2018, I had written Hina a Valentine. Inside the card was a typed poem. One of the lines went: When you aspire, I want to feel your desires — I would be your dreams — if I could be.",
        "I had written that line maybe a decade earlier. I did not know, when I wrote it, what year it would come true in. By God, in 2018 it came true. When Hina aspired in 2018, I felt her desires. I was trying to be her dream. I was doing my absolute best for her, for our eldest son, for the marriage we were carrying into its next phase. The magical year and the cracking year were happening inside the same body and inside the same marriage and inside the same eleven-hour car ride, and I was trying to be everything I had promised in that old Valentine to be.",
        "I was still trying. The trying was real. The trying did not save her.",
      ],
    },
    {
      type: "duaCard",
      label: "A du'a · on the year I did not know was the last year",
      arabic: "رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ",
      translit: "Rabbi awzi'ni an ashkura ni'mataka allati an'amta 'alayya.",
      meaning: "My Lord, inspire me to be grateful for Your favor which You have bestowed upon me.",
      gloss: "Surah An-Naml 27:19. The du'a of a man who has been given more than he can hold and is asking to be made adequate to it. I did not know in 2018 that the year was the year. I should have been more grateful. I am asking for the inspiration to have been.",
    },
    { type: "fpImage", eyebrow: "2017 · Mecca · Hina's 50th birthday", image: img("02_image"), alt: "Three figures before the Kaaba, Ahmad, Zanab, Hina, 2017", caption: "Three figures before the Kaaba — Ahmad, Zanab, Hina. Hina's 50th birthday trip, 2017. The last good year." },
    { type: "sectionCard", roman: "III", heading: "Her Notes", lede: "Pieces of paper in her handwriting that I found later. Some say All Attacks. One says Flashback. One says God Protect Us. The chronology of when she wrote them is not yet sorted — some may belong to the Franklin Road years and not the last year. They sit here as I found them." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "Hina wrote things down. She had written things down her whole life — the NC letters in 1984, the forced-abortion poem in November of that year, the love letters of the late 1980s, the 2009 leaving-note she walked back, the 2014 letter that is in Chapter Seven, the December 2015 birthday-of-Moaaz letter in Chapter Six. She wrote at three in the morning. She wrote on whatever paper was nearby. She wrote when no one was looking." },
        { kind: "plain", text: "After she passed, going through her things over the months and years that followed, I came across pages in her handwriting that I had not seen before. Some had titles. All Attacks. Flashback. God Protect Us. Others did not have titles. They are her voice without an audience. They are what was happening inside the body that was holding the household." },
        { kind: "plain", text: "I want to put what I have here, in this chapter, with the honest acknowledgment that I am still sorting which of these belong to her last year and which belong earlier — the 2006-onward Franklin Road years, when her parents were both gone and the dispute was eating at her. The placement chronology comes later. The notes are here because they are her hand and her voice and they belong wherever in the book they go." },
      ],
    },
    {
      type: "duaCard",
      label: "A du'a · in her own words, in her own hand",
      arabic: "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
      translit: "Hasbunā Allāhu wa ni'ma'l-wakīl.",
      meaning: "Allah is sufficient for us, and the best Disposer of affairs.",
      gloss: "Surah Āli 'Imrān 3:173. The verse said by the believers when the world tightened around them. Hina wrote God Protect Us in her own hand. It is the same prayer in two languages.",
    },
    { type: "sectionCard", roman: "IV", heading: "The Last Week", lede: "Thursday she found out about the valve. Friday Azmath came in the afternoon, and that night she said things. Saturday she went." },
    { type: "prose", lines: [{ kind: "drop-cap", text: "There was something about that week. There was something about that day and the day before and the day before that. They were not normal days. I am going to walk through them the way they happened, the way I remember them, because the sons and the grandchildren and whoever else reads this will want to know what the last days looked like from inside." }] },
    {
      type: "essayDrop",
      label: "",
      title: "Thursday, May 23, 2019",
      byline: "",
      paragraphs: [
        "Thursday Hina found out that the surgeon had made a grave error. The valve that had been put into her heart in her surgery was the wrong material. The surgeons had been specifically instructed to use the bovine valve — the cow material. She found out, that Thursday, that they had used porcine instead. The pig material. Not what had been asked for. Not what had been agreed.",
        "This caused her grief and pain like I had not seen in her in her life. Hina was not one to cry. She was not one to sniffle. She was freaking strong. In the years I had known her, including the worst of the worst years, she did not break that way in front of me. All Thursday she cried. All that Thursday did she cry. It broke me to watch it. There was nothing I could say. There was nothing anyone could say.",
        "She called the people she called. She called her older sister Naila. She called her younger sister Amina. She called her brothers. She called the kids. The phones were going all day. It was a bad bad day. It was a not good day. The whole family knew by sundown that something had been done to her body that should not have been done, and the something could not be undone.",
        "If anyone said anything she would not have heard it. It did not matter what was said. The best thing was to stay quiet. You do not come between Hina and her love for Allah subhanahu wa ta'ala. You do not come between Hina and her faith. You do not come between Hina and her relationship with her Lord. I do not care who you are — husband, brother, surgeon, doctor, lawyer, billionaire — you do not put yourself between Hina and God. That is what made Hina Hina.",
        "I stayed quiet. The room held the quiet. The day ended.",
      ],
    },
    {
      type: "essayDrop",
      label: "",
      title: "Friday, May 24, 2019",
      byline: "",
      paragraphs: [
        "Friday afternoon, Azmath Qureshi stopped by. Around three. He had been supposed to come a week and a half earlier and had finally made it. He came with his wife. They sat with Hina for an hour and a half, maybe a couple of hours, until five or five-thirty in the afternoon. Azmath is a wonderful person. Younger-brother personality. Very warm, very caring — the kind of person you call when there is no business reason to call. His wife is the same. A sweetheart. The two of them sat with Hina, and the room held them for those two hours.",
        "Then they left. The afternoon turned into evening. The evening was a tough evening.",
        "Hina was on the sofa in the TV room. She was agitated — understandably agitated, because she had found out about the valve the day before and her body was still her body and her body knew what she knew. She was not comfortable. She was not right. Hina was not one to complain about being uncomfortable. Even after surgery, even with the things her body had been through, she did not say I am uncomfortable. But that night she was visibly uncomfortable. It was hard to see. It was hard to be in the presence of. There was nothing to do.",
        "She was making comments. Around nine, around ten at night, sitting with me on the sofa, she said it repeatedly. She said: there's something in the house. There's something in the house. I don't know what's happening. There's something in the house. She kept saying it. I did not know what to say back. I did not say anything.",
        "Then she said: why didn't anyone from my family help me? Why didn't anyone from my family help me? She said it more than once. The lifetime she had been carrying since she was sixteen was surfacing through the body and through the agitation and through the night.",
        "Then she said: Abrar, what did we do? What did we do?",
        "I said to her: Hina, I know. I know. We fell, we got up, we pushed, we did some things we're not crazy about. But there's a lot of things we have to be proud of. And in the end there's Allah's mercy. That is what I said. That is what I had. It was not much. It was what was true.",
        "She was in another place that evening. Not unconscious — she was not going under. She was between two places. Somewhere in between here and not here. I have been in that place a couple of times in my own life. You are not here and you are not somewhere else — you are between. That is where she was for those couple of hours. From thirty years of marriage and forty years of knowing her, from the fragments she was saying, I understood enough to know where she was. I am not an expert on these things. This was my first experience of someone close to me being in that place. It will be my only experience of it with the one who was closest.",
        "Then the night ended. She slept. The next morning she woke up and she was back to normal. Which was nice. That was the thing about Hina — she would always come back. The morning after a bad night, she was Hina again.",
      ],
    },
    { type: "sectionCard", roman: "V", heading: "Saturday, May 25, 2019", lede: "Ramadan 20, 1440. One day after the Hijri birthday she and I shared. The day she went." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "I could go minute by minute through Saturday. Every minute of it matters to me. But for the book the short of it is enough. The short of it is the truth, and the truth does not need decoration." },
        { kind: "plain", text: "Saturday morning I was with her. Late morning, an hour and a half, in the bedroom. Just the two of us. We talked. I do not remember what we talked about. I remember being there. Then around one-thirty or two in the afternoon I went to the office. I was going to be there a couple of hours and come back." },
        { kind: "plain", text: "While I was at the office she texted me. She was hungry. Could I bring her something to eat. I texted back: sure, what would you like. She told me okra and something from Toros — the restaurant in New Milford. I told her okay, I would pick it up, I would be home in half an hour or forty minutes. She said okay great." },
        { kind: "plain", text: "She was not fasting. She could not fast because of the surgery and the recovery. Ramadan was on, but Hina was on medical leave from it. So I picked up the food from Toros and got home around five o'clock. I came in and went upstairs to the master bedroom." },
        { kind: "plain", text: "She was on the bed. She was on her back. Her legs were off the side of the bed. The position was weird. She was lying back with her legs off the side. Her eyes were closed. I took two steps forward to look more closely. I thought she was sleeping. The position was weird but I thought, let her rest. So I went back downstairs." },
        { kind: "plain", text: "Around six, six-fifteen, six-thirty, Amina and Ahmet came over for iftar. They were coming to see Hina, to sit with her, to spend the iftar with her sister. I went and sat at the table downstairs with Ahmet. We were chit-chatting, getting ready for iftar, preparing the food." },
        { kind: "plain", text: "Zanab came downstairs. I asked her: how's your mother? What's she doing? Zanab said: she's still sleeping. I asked her: in that weird position? Zanab said: yes. Okay. We continued waiting for iftar time, preparing the meal." },
        { kind: "plain", text: "A few minutes later I called Moaaz. Moaaz came down. I said: Moaaz, please go check on your mother — is she still sleeping? Moaaz went up. Moaaz came back down. He said: yes, she's still sleeping. I asked him: in that weird position? Moaaz said: yes." },
        { kind: "plain", text: "I got up from the chair to go check for myself. Slow. Heavy. I started up the stairs." },
        { kind: "plain", text: "On the walk upstairs is when I knew. Not at the table. Not when Zanab said yes. Not when Moaaz said yes. On the walk — one step, then another step, then another — I knew. The position had been wrong at five. The position was still wrong now. Hina did not hold that position. Hina did not sleep that way for fifteen minutes. The body was telling me on the walk up what the body had been telling me all along, and on the walk up I finally heard it. I did not think about it. I knew it. The two are not the same thing. Thinking comes later. Knowing comes when the knowing comes, and the knowing came on the stairs." },
        { kind: "plain", text: "I reached the master bedroom door. The threshold. Her." },
        { kind: "plain", text: "She was still in the same position. Both of her hands were up by her ears, palms facing out — the way you say Allahu Akbar. Her hands were small and dainty. Her fingers were semi-bent. Her pinkies especially — her pinkies were always bent, that was how her hands held themselves. The little cups of her hands. She had on her qameez. She did not have on her shalwar. Just the qameez, which on her went down to her shins, and her hands up by her ears in the takbeer position, and her legs off the side of the bed, and her face turned, and her eyes closed." },
        { kind: "plain", text: "I got closer. I touched her hand. She was gone." },
        { kind: "plain", text: "I yelled down: call 911. Call 911. I'm going to call 911. Ahmet, Amina, and Zanab came running upstairs. Moaaz had stepped out for a minute after iftar — he was not in the house when I yelled. Ahmet picked Hina up with Zanab and put her on the floor. Picked her up, put her on the floor. Zanab started doing CPR. Amina was on the phone, panicking, dialing 911. Ahmet took over the chest compressions." },
        { kind: "plain", text: "I did not stop anyone from doing anything. What else was there to do. Stay busy as much as you can. Do not second-guess. The knowing did not leave room for thinking. The thinking came later." },
        { kind: "plain", text: "The thinking came later that night. After the ambulance. After the hospital. After they pronounced. Sitting somewhere quiet, the way the mind goes back over a day when the worst thing has happened, the timeline put itself together for me. She had texted me at four-fifteen. She had wanted okra and something from Toros. I had told her I would be home in half an hour, forty minutes. I had walked in at five with the food. The position had already been the position by then. In the window between four-fifteen, when she texted me, and five, when I came in with the food, was when she went. I had been at the office. I had been on the way home with the okra she had asked for. She had texted me hungry and then her body had finished while I was driving with her okra in the car, and by the time I reached the bedroom she was already gone, and I had read the gone-ness as sleep and left her there for two and a half more hours." },
        { kind: "plain", text: "That is the timeline as I understood it later. On the stairs I had only known she was gone. I had not yet known the window. The window I figured out that night, with the day in my head, and the okra in the trash, and Hina at the hospital." },
        { kind: "plain", text: "The ambulance arrived. I was discombobulated. I did not know anything. I was seeing things. My brain was here and there. From the outside I was not visibly going under. From the outside I was Abrar. Inside there were hurricanes and tornadoes and volcanoes and monsoons and tsunamis. All of it. That was Hina — outside calm, inside everything." },
        { kind: "plain", text: "We followed the ambulance to the hospital. Half an hour, forty-five minutes later, they pronounced. She had passed." },
        { kind: "plain", text: "From that moment on I was lost. It is not the way it was supposed to be. It is never the way it was supposed to be. When I was eighteen I did not think I was going to make it to thirty-five — the life I was living, the way I was — but God had other plans, and I made it past thirty-five and past forty and past forty-seven and Hina was supposed to be next to me for all of it. The husband goes first. The husband goes first and the wife remains. That is how I thought it was supposed to go down. That is not how it went." },
      ],
    },
    { type: "pullquote", lines: ["Her hands were up by her ears,", "palms facing out,", "the way you say Allahu Akbar."], src: "May 25, 2019 · the master bedroom" },
    {
      type: "duaCard",
      label: "A du'a · for the one we return to Him",
      arabic: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ",
      translit: "Innā lillāhi wa innā ilayhi rāji'ūn.",
      meaning: "Indeed we belong to Allah, and indeed to Him we return.",
      gloss: "Surah Al-Baqarah 2:156. The verse you say when you hear of a death. We had said it about other people for decades before we had to say it about her. I have said it every day since.",
    },
    { type: "sectionCard", roman: "VI", heading: "The Night and Sunday", lede: "One call to Azmath. Maybe one to siblings later, I do not recall. Quran recitation through the night. Burial by noon on Sunday, May 26. Ramadan. Memorial Day weekend. She would not have wanted anyone to be a bother for her." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "I did not make many calls that night. Maybe one to siblings later in the evening — I do not recall. The one call I clearly remember making was to Azmath Qureshi. I called him and said: Azmath, Hina passed. Please come. Bring the Quran. Bring your cousins. When Azmath's father had passed some years before, I had seen what he and his cousins did — they sat in the room with the body and recited Quran through the night. That was what I knew to do for Hina. So I asked Azmath to come." },
        { kind: "plain", text: "From there, Yasmin Hammeeduddin and Zarrar took over. They handled what needed to be handled. It was nine, ten at night by then. Everything from that point forward is a fog to me. I was there but I was not there. I was Abrar on the outside doing what had to be done. Inside I was somewhere I do not have words for." },
        { kind: "plain", text: "By noon or one o'clock the next day, Sunday May 26, 2019, she was buried." },
        { kind: "plain", text: "It was Memorial Day weekend. It was Ramadan. It was a Sunday. Nobody had to take off work. Nobody had to call in. Nobody had to rearrange anything. Hina would have wanted it exactly that way. She would not be a bother to anybody. She would not be a burden on her way out. Before her surgery and after her surgery she had been making the du'a: do not let me be a bother or a burden on anyone. Her du'as were answered." },
        { kind: "plain", text: "The ghusl — the washing of her body — was done by Zanab, my daughter, and by Amina, Hina's youngest sister. Aisha, Karrar's wife, who is also Hina's cousin, was there. Tayyaba, Zarrar's wife, was there. I believe there was an older auntie there with them for instruction. The ghusl was done at Nida ul Islam — the second community masjid — because Hina had been adamant that her ghusl be done there. The janazah prayer was also at Nida ul Islam." },
        { kind: "plain", text: "Then we drove her up to the cemetery. The cemetery is in upstate New York, near Woodbury Commons, about forty-five minutes to an hour from Teaneck. It is the same cemetery where Hina's mother — Auntie Beg — is buried. When Auntie Beg passed in 2006, Hina and I had taken on organizing the family. We had said: let us buy plots while we have the chance. We asked who else wanted to be in on it. We bought three. Zarrar bought plots too. Karrar and Amina joined in. Altogether the family bought somewhere around ten or twelve plots. By the time Hina was buried, five of them were used — Auntie Beg, Zarrar's daughters, and now Hina." },
        { kind: "plain", text: "Shahbaaz rode in the hearse with the body. I do not remember who else was in the hearse. I drove by myself. I do not remember where everyone else was. I remember the road." },
        { kind: "plain", text: "The body is washed and wrapped in three pieces of white sheet. Because of the cemetery policies in America, the wrapped body is placed in a plain pine box. We did all of that. The hole was already dug. We lowered the box into the grave. We tilted the body toward the east. The face facing east, toward the qibla. I did that with my own hands." },
        { kind: "plain", text: "The first shovels of dirt fall to the husband. That is how it is done. I started shoveling. I wanted to shovel all of it myself. I would have shoveled the whole grave closed if Mufti Abdul Muqtadir — the imam of Nida ul Islam — had let me. He did not let me. I wanted to argue. I wanted to fight. I wanted to fight everybody that day, because I did not know what to do with what I was feeling, and fighting is love, and I did not know where else to put it. But I had to be respectful. So I shoveled what I shoveled and then the rest of the men took over — friends, family, brothers, sons, nephews. Everyone took a turn. The grave was filled." },
        { kind: "plain", text: "Afterwards, the way it is done, we walked away from the grave a hundred yards. We all did that. Then I walked back. I sat at the grave for a couple of hours. I sat there just absorbing what I had just done. What had just been done. What was now done." },
      ],
    },
    { type: "pullquote", lines: ["I wanted to shovel the whole grave closed.", "I would have, if he had let me."], src: "May 26, 2019 · at the grave" },
    {
      type: "asideCard",
      label: "A note · on the people who came",
      heading: "People I had not seen in fifteen, twenty years",
      paragraphs: [
        "I do not know how everyone found out so quickly. Twelve hours between her passing and the burial. People I had not seen in fifteen years, twenty years, showed up at Nida ul Islam for the janazah. I do not know how the word traveled.",
        "There are three reasons for it. The first is the barakah of Hina herself. She was a quiet person but she was not the kind of person you meet and forget. Her high school years, the people who lived through them with her, her co-workers, her bosses, anyone who had spent ten minutes in a room with her — you did not forget her. Her style, her radiance, her dignity, her presence. That is reason one.",
        "The second is that she is Khalid Beg's daughter. Uncle Beg meant everything to everyone in our community. Father figure, big brother, imam, the one who taught us suras and knowledge that had nowhere else to come from in those years. Not just to the younger generation — even the uncles in our parents' generation went to Uncle Beg. So when his daughter was being buried, it was not just Hina's funeral. It was Uncle Beg's daughter's funeral. People came for him as much as for her.",
        "The third is the Beg family itself. The siblings, the wider family — well-known, well-placed in the community over decades.",
        "Some of the people who came probably did not even know I was the husband. There is a whole faction — people who came to Teaneck in the mid-nineties or the two-thousands — who would have no idea who the husband was. I was the low-key one. I am the low-key one. That is fine. The community came for Hina. The community came for Uncle Beg's daughter. That is what the community should have come for. I was there. I was the husband. I knew where I stood.",
      ],
    },
    {
      type: "asideCard",
      label: "A note · on the count",
      heading: "The fifth most important man in her life",
      paragraphs: [
        "I have said this elsewhere in the book and I want to be precise about it here. In Hina's life there was a count, and the count went like this:",
        "First, Rasulullah, sallallahu alayhi wa sallam.",
        "Second, Abu Bakr radiyallahu anhu, the first Caliph.",
        "Third, Umar radiyallahu anhu, the second Caliph.",
        "Then a flip-flop between her father, Khalid Beg, and me. Some days he was fourth and I was fifth. Some days the order swapped.",
        "I never minded. I never resented the count. Alhamdulillah, after the Prophet and the first two Caliphs and her father in any order — that is a beautiful standing. I knew where I stood. I was where I wanted to be. To be in any rank in Hina's life that had those four names ahead of me was an honor. The honor is the placement, not the number.",
        "The husband is fifth, sometimes fourth. He is grateful for that placement. He would not have wanted to be anywhere else in the order. He understood the order the woman he loved was holding herself to, and he was proud of her for holding it, even when it meant he stood behind four other men in her count.",
      ],
    },
    {
      type: "duaCard",
      label: "A du'a · from the janazah prayer",
      arabic: "اللَّهُمَّ اغْفِرْ لَهَا وَارْحَمْهَا وَعَافِهَا وَاعْفُ عَنْهَا وَأَكْرِمْ نُزُلَهَا وَوَسِّعْ مُدْخَلَهَا",
      translit: "Allāhumma'ghfir lahā wa'rhamhā wa 'āfihā wa 'fu 'anhā, wa akrim nuzulahā wa wassi' mudkhalahā.",
      meaning: "O Allah, forgive her, have mercy on her, give her peace, and absolve her. Receive her with honor and make her resting place spacious.",
      gloss: "From the janazah prayer over a woman. I said this over Hina at Nida ul Islam. I have said it every day since. I will say it every day for the rest of my life. It is the only thing left to do for her in this world.",
    },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "For two weeks after the burial I went to the cemetery every day. Every single day. Sometimes for hours. Sometimes I just sat at the grave and did not speak. Sometimes I read Quran. Sometimes I said her name. Sometimes I said nothing." },
        { kind: "plain", text: "I went the next day. And the next day. And the next day. And the next day. And the next. Two weeks of going to be close to her. That was all I could do. The household was full of people but the house was empty of her. The cemetery was empty of people but full of her. So I went where she was." },
        { kind: "plain", text: "That is how the first two weeks passed. The phone calls had their own life. The community had its own life. The kids had their own grief. I went to the grave. I did the only thing I could do for her. I sat there. I asked Allah subhanahu wa ta'ala to forgive her, to be merciful to her, to give her peace." },
      ],
    },
    {
      type: "asideCard",
      label: "A note · on the spreadsheet I opened that week",
      heading: "The should-have document",
      paragraphs: [
        "Within the first week after Hina passed, I sat down and opened a Google Sheet. I wrote down what I called the should-have document — between myself and her. What I could have done. What I should have done. Where I fell short. What I had been expecting from her. What I had been pissed off about. Where I should have been gentler and warmer.",
        "I had thought we had more time. Not because we were young — I was forty-seven, she was fifty-two, the eldest was getting married, the household was about to enter the next phase. I had thought the focus would shift back to the family. The building of the businesses was the work we had been doing for two decades; that time was ending. I was scaling back. We had been waiting for this phase. We were about to enter it.",
        "That was not what happened. What was to be was what was to be. So I sat down and wrote the should-have document. I do not know if it belongs in this chapter or somewhere else in the book. I am putting a note here that it exists, and that I wrote it that first week, because the reader should know that the husband's first reflex, in the week after his wife of thirty years passed, was to sit down and itemize where he had fallen short. That is the kind of husband he was trying to be. That was the worship the writing had become.",
      ],
    },
    {
      type: "artifactRow",
      rowLabel: "The Last Year, in Her Hand",
      heading: "Five notes Hina left behind, 2018–2019",
      intro: "She was still writing in her last year. Short, sharp, no rhetoric. The notes are the unedited inside of what was leaving the house.",
      items: [
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811255/buyahka-abrar/drive-docs/1ILchl0QiP4N6rtG6j37AVCsDOB03brem.jpg", alt: "Hina's last-year note: All Attacks", caption: "\"All Attacks.\" The note that names the cumulative weight." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811277/buyahka-abrar/drive-docs/1nzIxJiK3O3wvpNmZIzneaIeRlIwXuq5H.jpg", alt: "Hina's last-year note: Flashback", caption: "\"Flashback.\"" },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811300/buyahka-abrar/drive-docs/1teapt2QC-_RGlsVFLFusRCPUFCi6hyIv.jpg", alt: "Hina's last-year note: God Protect Us", caption: "\"God Protect Us.\"" },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811313/buyahka-abrar/drive-docs/1-xfTpEVkiUz9-xsm0PB7PZWGU4jk34Ei.jpg", alt: "Hina's last-year note: 89 Franklin Rd", caption: "\"89 Franklin Rd.\" The address where she grew up, where she came back, where her father stood with her one last time at her second wedding." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811280/buyahka-abrar/drive-docs/1pkJqDB9nqJoT6slR33w-I3wQgj7gzJWO.jpg", alt: "Hina's last-year note: 8-3-18 (786 / spine sentence)", caption: "August 3, 2018. The 786 note. The spine sentence of the last year." },
      ],
    },
    {
      type: "artifactRow",
      rowLabel: "The Keeping",
      heading: "What she gave, what was kept",
      items: [
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811298/buyahka-abrar/drive-docs/1tdTOJatG_XgLBU7ip8XzlPbglzYHmDpC.jpg", alt: "Ahmad and Hina's wedding photograph, November 10, 1989", caption: "Ahmad and Hina, November 10, 1989. Mehr $1,000, payable when demanded. The contract held until May 25, 2019." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811266/buyahka-abrar/drive-docs/1lX-NScpSzkvv4Z9ZHg_qoFN1ga936eWM.png", alt: "Hand-drawn sketch of Hina and Zanab", caption: "Hand-drawn sketch of Hina and Zanab. Mother and daughter." },
      ],
    },
    {
      type: "artifactRow",
      rowLabel: "Her Face, Her Voice in Motion",
      heading: "What was in the house until May 25, 2019",
      items: [
        { imageSrc: "https://drive.google.com/thumbnail?id=1Mv9j6K_t7jh9W1sXrRtmefDcL7SYtTAh&sz=w1200", alt: "Hina with mirror", caption: "Hina, in mirror." },
        { imageSrc: "https://drive.google.com/thumbnail?id=1cNnPbHDjg4r0eObDnSfz0pUFzZfFzE7o&sz=w1200", alt: "Hina close up, latest", caption: "Close up." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789886453/buyahka-abrar/drive-docs/1CHz7_5CjY0118D7-rTiHeQVW2HlsklHf.jpg", alt: "Hina close up, seaside", caption: "Seaside." },
        { imageSrc: "https://drive.google.com/thumbnail?id=17LobIEGBds6hiq9n1EPU0w76yy_8gtrv&sz=w1200", alt: "Hina portrait", caption: "Portrait." },
        { imageSrc: "https://drive.google.com/thumbnail?id=11B-VhGHXl1yJ09kKa0NWkJeKePQuBexk&sz=w1200", alt: "Hina in red", caption: "In red." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789886454/buyahka-abrar/drive-docs/1F52n3TdM9uU57EdxBzuxpf3FbQE8-39s.jpg", alt: "Hina with closed eyes", caption: "Closed eyes." },
      ],
    },
    {
      type: "driveVideo",
      label: "Video · the core memorial",
      heading: "Hina — the memory video",
      src: "https://drive.google.com/file/d/1z4kr3zmspAOgXozNKjaf5LdskekW6bXi/preview",
      caption: "The core continuity video. Her face in motion. Her presence still moving across the room.",
    },
    {
      type: "driveVideoRow",
      rowLabel: "In Motion",
      heading: "Living-relationship footage",
      items: [
        { src: "https://drive.google.com/file/d/18GEWSX6wy5bPr-HwJw4gs0Gv8Q-yXmDZ/preview", caption: "Hina and Ahmad smiling." },
        { src: "https://drive.google.com/file/d/1zE4RReY-DqP88veKtLm0mWhv0TQIbO6X/preview", caption: "Hina and Ahmad walking together." },
        { src: "https://drive.google.com/file/d/1u5Lkzql7wmUJsmESGDT_cxWUOLNAw_ZY/preview", caption: "Hina smiling." },
        { src: "https://drive.google.com/file/d/1Hkl5SYmOzGSOdblZIZjzZ2Mm4HCHApWy/preview", caption: "Hina — gorgeous smile, with the American flag." },
      ],
    },
    {
      type: "artifactCard",
      label: "May 26, 2019",
      heading: "The burial",
      imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789886455/buyahka-abrar/drive-docs/1-YmFt3hImsDhZZZJPmCAHoE2PJyTbIuJ.jpg",
      alt: "Hina's grave, burial May 26, 2019",
      caption: "The morning after. The ground that holds her now.",
    },
    { type: "chapterEnd", nextTitle: "Chapter Nine — Six Months Later" },
    { type: "fpImage", eyebrow: "May 26, 2019 · the day of burial", image: img("03_image"), alt: "Hina Beg, 1/17/1967 – 5/25/2019, age 52, covered in roses", caption: "Hina Beg · 1/17/1967 – 5/25/2019 · Age 52. Covered in roses, the morning after." },
  ],
};

export default chapter08;
