import type { MemoirChapterContent } from "@/lib/memoirBlocks";

// Transcribed verbatim from leg/chapter_05.html (the package Ahmad approved).
const FOLDER = "buyahka-abrar/chapter-05";
const img = (n: string) => ({ publicId: `${FOLDER}/${n}`, resourceType: "image" as const });
const vid = (n: string) => ({ publicId: `${FOLDER}/${n}`, resourceType: "video" as const });

const chapter05: MemoirChapterContent = {
  number: 5,
  slug: "chapter-5",
  title: "The Flower Shop",
  soundtrack: {
    name: "Chapter 5 — Building Life",
    tracks: [{ media: vid("03_audio"), title: "Anita Baker — Giving You the Best That I Got" }],
  },
  blocks: [
    {
      type: "hero",
      book: "Buyahka and Abrar",
      chLabel: "Chapter Five",
      title: "The Flower Shop",
      em: "Teaneck Road, 1986–1996",
      subtitle: "She walked past it on her way to Food Town. She walked into it and asked for a job. Ten years later, two weeks before Valentine's Day, we bought it.",
      meta: "Part II — Building",
    },
    {
      type: "poem",
      title: "She is the girl I grew up with",
      translit: "From \"A True Wife\" · August 13, 1991",
      stanzas: [{ lines: ["She is the girl I grew up with,", "she is the lady I love.", "She is the woman who is now,", "my wife."] }],
    },
    {
      type: "prose",
      lines: [
        { kind: "opener", text: "Two weeks before Valentine's Day, 1996, the deed to Teaneck Flowers changed hands. The shop had been Peter Tournas's. Now it was ours. Hina was eight months pregnant. Zanab would arrive on March 25, six weeks after the closing. The shop had a busy season ahead of it. The new owners had a baby ahead of them. Both came on time." },
        { kind: "drop-cap", text: "The shop was on Teaneck Road. Hina's family had lived a few blocks away on Franklin Road for as long as I could remember — since we moved to Teaneck. They had lived in a few other places in the area before that. She walked past Teaneck Flowers regularly — on the way to Food Town five hundred yards down, on errands for her mother, on whatever ordinary trips a girl makes through her own neighborhood. The shop was part of the daily route long before it became part of the daily life. In February 1986, at nineteen, four months back from Durham and looking for somewhere steady, she walked in and asked Peter for a job. Peter hired her." },
        { kind: "plain", text: "Peter Tournas was a Greek man, older, decent. He owned three flower shops; Teaneck was the strongest. He ran them honestly. Things changed at Teaneck in some periods because of partners he brought in — the way of small businesses everywhere — but Peter himself was a good man, and he gave Hina a counter to stand behind in a year when standing somewhere steady was its own kind of medicine. She was good at the work. She was articulate, dedicated, diligent. She brought the kind of attention that customers feel even when they cannot name it. She was, plainly, a blessing to Peter. He knew it." },
        { kind: "plain", text: "I joined the shop in February 1988, twenty-one months before my nikah to her. I was sixteen. She put me on the payroll. She taught me the register. She taught me how to take a wedding order over the phone. She taught me how to write a delivery slip. From 1988 forward I was running a strange schedule — the shop during the day, two other jobs alongside it. Night school would come later, after the nikah, once I had my papers in order. I was a father at nineteen. The hours had to come from somewhere. I did not sleep much." },
        { kind: "plain", text: "Hina worked at the shop full-time roughly two to three years — through 1989, into the early period of motherhood. After Moaaz arrived in December 1990 she stepped back to part-time. The shop did not need her at the counter every day; it needed her institutional memory, which lived in her head and traveled with her wherever she was. By 1991 I was twenty, two years married, running the floor without her present, calling her at her parents' or wherever she had gone with our infant son to ask her how to do the billing. I have a letter that says exactly this. I will get to it in a moment." },
        { kind: "plain", text: "What I want to set up first is how we ended up owning the place at all. The honest version is shorter and less neat than the version a memoir prefers. Peter was not retiring. The original plan was not Teaneck." },
      ],
    },
    { type: "sectionCard", roman: "I", heading: "How We Ended Up Owning It", lede: "I was going to buy the Hackensack store. My brothers walked me through the math. The math walked me to Teaneck." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "In 1995 I was ready to do something on my own. I had tried, in 1991 and after, to get out of the flower business. The Gulf War recession had killed most of the doors I had knocked on. I took civil-service tests to keep options open. I considered becoming a policeman. None of it landed. The flower business stayed." },
        { kind: "plain", text: "By the mid-nineties I knew the business cold. I had been at Peter's for seven years. I had worked the front and the back. I had run wedding accounts, funeral accounts, holiday rushes, every wire-service order that came over the line. I was twenty-four. I was ready to own something. I went to Peter and asked." },
        { kind: "plain", text: "Peter had three shops. The Hackensack store was one of them. It was the smaller of the three — a smaller customer base, a smaller lease, a smaller price tag. It was what I could afford on my own. Peter was open to selling Hackensack. He would not have wanted to sell Teaneck, his strongest store, to a young employee who was three years on his own from a duffel bag of clothes. The plan I walked into Peter's office with was the Hackensack plan." },
        { kind: "plain", text: "Before I shook on it I called my eldest brother. Basit. I told him this is what I am about to do, I can do it, I just want to run it past you. He said yes. He said good. He told me to call a family in Connecticut who owned a flower shop. They had numbers. They could look at my numbers. A second set of eyes. I called them. They walked me through the analysis. The Hackensack numbers worked." },
        { kind: "plain", text: "Then my middle brother got involved. Assad. He looked at the same numbers. He spent maybe ten minutes with them. Then he said: Why are you buying Hackensack? I told him because that is what I can afford. He said: Why don't you buy Teaneck. The strong store. I said because the price is going to be much more, and because I do not think Peter wants to sell that one — that is the one a man keeps. Assad said: Let me talk to Abba. See if there is a way. Assad went to our father. They looked at it together. There was a way." },
        { kind: "plain", text: "Not a comfortable way. A way that involved leaning on our father for a portion of the financing, leaning on Peter for a portion, and accepting that the next several years would be tighter than they would have been on the Hackensack track. Ikram Koshul, sixty years old at that point, the same man who had taught me by example to do hard things without making a fuss about them, said yes. I went back to Peter with the new plan. Peter, to my surprise, was for it. He had other business he wanted to go into. He could use the funding from a Teaneck sale to do it. Hackensack was not what he was looking to free up. Teaneck was." },
        { kind: "plain", text: "So we bought Teaneck. The reason we bought Teaneck and not Hackensack was that my older brothers, in two separate phone calls, refused to let me settle for the smaller store. The reason we could afford Teaneck was that my father said yes. The reason Peter said yes was that he had his own plan. Four men, plus a family in Connecticut, made the deal possible. A young couple stood at the closing and signed." },
        { kind: "plain", text: "I want to name this honestly: we did not buy a building on the strength of our own balance sheet. We bought it on the strength of older men who had decided, separately, that the kid was worth backing. Basit and Assad on the family side. Ikram on the financing side. Peter on the seller side. The kid was the one who would carry the work. The older men carried him to the door." },
      ],
    },
    {
      type: "asideCard",
      label: "A note on the brothers",
      heading: "Why Assad's ten minutes mattered",
      paragraphs: [
        "Basit said yes to the plan I brought him. That was the older-brother thing. Assad refused it and made me bring a better plan. That was the other older-brother thing. Both of them were right at the same time, in different ways, and the marriage of the two responses is what got the deal done.",
        "I have been the recipient of that doubled love most of my life. The older brothers do not say so. The younger brother is the one who has to write it down.",
      ],
    },
    {
      type: "duaCard",
      label: "A du'a · on the signing",
      arabic: "اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
      translit: "Allāhumma ikfinī bi-ḥalālika ʿan ḥarāmik, wa aghninī bi-faḍlika ʿamman siwāk.",
      meaning: "O Allah, suffice me with what is halal instead of what is haram, and make me independent, by Your grace, from anyone besides You.",
      gloss: "The kid signed papers he could not pay for, on financing he had not earned. This is the prayer he carried into that closing.",
    },
    { type: "sectionCard", roman: "II", heading: "A True Wife", lede: "August 13, 1991. School essay. Two years married. Eight-month-old son. The earliest I ever wrote about her on paper." },
    {
      type: "prose",
      lines: [{ kind: "drop-cap", text: "In August 1991 I was nineteen and given a school assignment: write about someone important. I wrote about Hina. I want the essay reproduced inside this book in full because it is the earliest writing I have on her. The teacher gave it an A. The teacher's marginal note — that some passages could have been more descriptive and personal — was about specific lines where I had decided not to share what was in my head. Some things are between husband and wife. They still are." }],
    },
    {
      type: "artifactCard",
      label: "Artifact · in Ahmad's hand · age 19",
      heading: "A True Wife — page 1 of 4",
      imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811226/buyahka-abrar/drive-docs/1ADhtMvENkfZ-dWIDwQu9f4VRxaSSgX3X.jpg",
      alt: "Handwritten first page of A True Wife essay, dated 8/13/91, by Ahmad Koshul, age 19",
      caption: "The opening page of the essay in the boy's handwriting. Dated 8/13/91 in the upper-right corner. The teacher's marginal notation is visible. The full text follows in print.",
    },
    {
      type: "essayDrop",
      label: "A True Wife · in full",
      title: "A True Wife",
      byline: "By Ahmad Koshul · August 13, 1991",
      paragraphs: [
        "The best thing that could possibly happen to a man is to be blessed by a true wife.",
        "We men have relationships with women such as son and mother, father and daughter, brother and sister. However, the relationship between a man and wife is unique. A wife is one to whom we can bare our soul with absolutely no regret. She is the one to whom we turn at our utmost time of need. It is to her that we promise \"till death do we part.\" We all have our different interpretations of a true wife. My interpretation's name is Hina. She is the girl I grew up with, she is the lady I love. She is the woman who is now, my wife.",
        "As we grew up together, I discovered that Hina was so innocent and so pure. She was a bundle of joy whose eyes twinkled like tiny stars. She had a smile which was remarkably genuine and sincere. Never had I seen a girl who was adored by everyone in such a great measure. The energy and charisma which she had within her would have surely brought light to the darkest imaginable places. She was a delightfully darling princess whose unblemished personality, not even the angels could equate.",
        "As time went by, I discovered that Hina, the lady I had learned to love, was a portrait of perfection and of beauty. She changed from an adorable girl into a majestically enticing goddess, to whom there was no equal. Our relationship transformed from friendship into love. I have never seen a lady that was so elegant and refined. She was so delicate, yet her personality so vibrant. Her eyes would glisten like pearls, as the soft rays of the moonlight would emulate off of her trance-inducing, charming eyes. She possessed such a ladylike smile which would melt any man's heart. A walk which was so gracefully exquisite only she could possess. Her hair was jet black and magnificently fine. The brilliance of her golden skin was lustrously smooth. This was the lady to whom I fell in love.",
        "Hina, the woman who is now, my wife has become my sole sustenance. She is a wife who is very pleasant company. She is considerate and compassionate, understanding and sweet. Our home is her domain in which she is the queen. She is the backbone and pillar of our family. She is the most trustworthy person whom I have ever encountered. Her morals, values and patience are those of a saint. Our son will most definitely grow to manhood in an atmosphere permeated with family love thanks to her devotion to him and to myself. She is very tolerant, courteous and thoughtful, so much so that she is an inspiration to me.",
        "Hina is a woman whom I, merely, can not compliment enough. To keep away from the temptations of the immoral and sinful society of today is a tremendous task which she is accomplishing with great ease. It is an honor for myself to be able to spend my life with someone whom I consider to be the ideal wife. She has such a flawless personality which is in all ways admirable. Hina is a true wife. She is truly a blessing to myself and my son.",
        "I wrote about Hina because there is not anything or anybody that I know better. She is very important to me.",
        "It was hard for me to get my thoughts together. I spent hours thinking of the right words to use, to make the essay flow. I liked reading it over and over. I guess. If I could change it, I would make it more descriptive and be more personal.",
      ],
    },
    { type: "sectionCard", roman: "III", heading: "Two Letters Home", lede: "She had gone with our son to her brother Zarrar's wedding. I wrote her two letters from the empty house. I signed the second one Ahmad-Abrar." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "The same August she had also gone away — she had taken our eight-month-old son and traveled to her brother Zarrar's wedding. I do not remember now exactly how long she was gone. The shop did not stop. The customers did not stop. The bills did not stop. The kid did not stop missing her. I wrote her two letters during that absence, and twenty-one months into the marriage, in the language of a young man with a weak vocabulary trying to say something he did not yet have the words for, I told her things I had not told her before." },
        { kind: "plain", text: "The first letter was five pages. I wrote it the day she left. About 21 months ago I married you, about 9 or 10 years ago I decided you were the Lady I wanted to be my wife. I want you to do the arithmetic. Nine or ten years before August 1991 was 1981 or 1982. I was ten or eleven. The decision a grown man was naming in a letter to his wife had been made by a child sitting on a burnt orange couch." },
        { kind: "plain", text: "I told her things in that letter I had not been able to tell her before. Before we got married there was a time span of about 4 to 5 years in which I forgot why I loved you but I did remember you were the one I had to get married to. The four-to-five-year span was 1985 to 1989 — her first marriage, her North Carolina years, her return, my homelessness, the rebuilding. The feeling went dim. The decision held. You even asked me why I did not have a sincere answer. You thought maybe it was a rivalry I had with my brother or I wanted to get back at my Family. She had not believed me. She had thought I was using her to spite someone. I could not, at the time, articulate the real reason. The real reason was that I had decided as a child and never undone it." },
        { kind: "plain", text: "I told her: I have a very weak vocabulary so I can not express myself the way I want to. I was naming my own limit on the page. The honesty was the gift." },
        { kind: "plain", text: "I told her also: I beg of you please take care of my son please, Hina. If anything should happen to him I would go crazy. The eight-month-old was Moaaz. The boy who would grow up to read this book." },
        { kind: "plain", text: "And I asked, in business voice in the same letter: Please send step by step directions on how to do the billing for TFS. Love and the ledger in the same letter. The flower shop and the marriage in the same envelope. They were not separate compartments. They never had been." },
        { kind: "plain", text: "The second letter was shorter. Two pages. Sent later in the same trip with a questionnaire enclosed for her to sign and FedEx back. I had run out of paper for tenderness and was running on need. I wrote: Please strengthen your personality so that I can stand straighter. A nineteen-year-old husband asking his twenty-four-year-old wife to be a stronger spine for him to lean on. The dependency was honest. The marriage carried it because she was strong enough." },
        { kind: "plain", text: "And then, in the same letter, the line that named the whole rest of this book before I knew there would be a book:" },
        { kind: "center-italic", text: "I had forgotten my entire life before 1987-88 and now for some reason the years before that come to my mind a lot more often than they used to." },
        { kind: "plain", text: "I thought that the old Abrar had passed away, I wrote, but every now and then I swear I feel him inside of me trying to express himself but he can not. Buyahka the builder, Abrar the soul — already named in 1991, in a letter from an empty house." },
        { kind: "plain", text: "I signed that second letter Ahmad - Abrar. The two names side by side, with a hyphen between them. The merged self. He was already trying to be both at once." },
      ],
    },
    { type: "sectionCard", roman: "IV", heading: "Alone I Have Been", lede: "She wrote me a love letter, undated. No salutation. No signature. Just the words. I have read it a thousand times." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "There is a single page in Hina's handwriting in the archive of this marriage. No date. No greeting. No closing. Just the words. I do not know what year she wrote it. I do not know if she handed it to me or left it where I would find it. I do not know if she meant for me to keep it forever. She did not write a draft of it — this is the only copy. She did not sign it." },
        { kind: "plain", text: "I am going to put it here as she wrote it. The double underline on one word is hers. The pacing is hers. I will not interrupt it. After it I will say one thing." },
      ],
    },
    {
      type: "essayDrop",
      label: "Hina · undated · in her own hand",
      title: "Untitled",
      byline: "",
      paragraphs: [
        "Your company gives me peace and serenity. No one else like you, to me. The comfort, support and strength that I feel from your decency.",
        "I may seem to be a pest and desire you — more than you care to be desired.",
        "But my need is what makes me desirous of you: the need of goodness. The need of peace. The need of a silent understanding. Your voice and looks are additional; but secondary — and all else.",
        "To know that you are — makes me whole and complete. Alone I have been and you've ALWAYS been the filler of the hole.",
        "So please forgive my need, and accept my appreciation.",
      ],
    },
    {
      type: "artifactCard",
      label: "Artifact · in Hina's hand · undated",
      heading: "Alone I have been — the letter itself",
      imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811287/buyahka-abrar/drive-docs/1RdFlhA7Bg0UKLydNaqnduDjuAteyMe0K.jpg",
      alt: "Hina's handwritten love letter to Ahmad, no date, no salutation, no signature, with the word ALWAYS double-underlined",
      caption: "Her actual page. Her actual handwriting. The double-underlined ALWAYS visible at center. No date, no greeting, no closing. Only the words.",
    },
    {
      type: "prose",
      lines: [
        { kind: "plain", text: "The thing I have to say is this. The double-underlined ALWAYS is the most important word in our archive. She is asserting that I had filled the hole in her not occasionally, not sometimes, not most of the time, but always. I do not believe I had earned it. I believe she had decided to credit me with it. There is a generosity in her telling me so that I do not know how to repay. The page is in this book in part as a debt I am acknowledging cannot be repaid, only honored by being written down where it can be read." },
        { kind: "plain", text: "\"Your voice and looks are additional; but secondary.\" She is naming what she values and what she does not. She did not love me for my voice. She did not love me for my looks. She loved me for what she calls, in the same letter, decency. That is the cleanest naming of a marriage I have ever read." },
      ],
    },
    { type: "sectionCard", roman: "V", heading: "Who She Already Was", lede: "The poster was made before her first marriage. Before any of this. It is the evidence of a consciousness that arrived early and did not need anyone's permission." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "There is a poster in the archive that I want to show you here, even though it predates everything in this chapter. Hina made it sometime around 1980 or 1981 or 1982, somewhere in those years before her first marriage. She was thirteen, fourteen, fifteen. The poster is a single sheet, decorated in colored markers. Rules for handling the Qur'an, fanned out from a central blank space in a sunburst pattern. The word at the center was meant to be RESPECT." },
        { kind: "plain", text: "I am putting it in this chapter, the chapter about the years we built the shop and the household, because the woman I was building with was already this woman before I built anything with her. She did not become this in our marriage. She arrived as this. A teenage girl, putting careful adab on a single sheet in colored marker, before she had been married, before she had been broken, before she had returned. The consciousness was already complete." },
        { kind: "plain", text: "If you want to know who she was, you do not start with what was done to her at sixteen. You start with what she was making at thirteen. Read her poetry from 1976 forward. Note the ages. Put it together for yourself." },
      ],
    },
    {
      type: "artifactCard",
      label: "Artifact · in Hina's hand",
      heading: "RESPECT — Qur'an Adab Poster",
      imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811261/buyahka-abrar/drive-docs/1J30rYAExct_jnYw4cZhlhEbmbSR0n-8J.jpg",
      alt: "Hand-drawn poster in colored markers radiating rules of adab around a central blank space meant to read RESPECT",
      caption: "A single sheet, colored markers, rules for handling the Qur'an arranged in a sunburst around a center meant to read RESPECT. Made by Hina sometime around 1980–1982, in her early teens. Before her first marriage.",
    },
    {
      type: "asideCard",
      label: "Aside · 1988",
      heading: "What a woman watches on television at seventeen",
      paragraphs: [
        "In 1988 I bought her a red Camaro with T-tops. Not because I wanted a flashy car. Because she loved Knight Rider. The black Trans Am that talked. Hasselhoff. The show ran from 1982 to 1986; she watched it through her late teens, fifteen into nineteen, the same years the first marriage was happening to her. She loved it anyway. So when I had a chance, at seventeen of mine, I bought the closest thing I could find to KITT in red. T-tops because she liked the open sky.",
        "What a woman watches on television at seventeen is what a man with a slow hand buys her at seventeen.",
        "That is what attention looks like. Most men do not pay it. Some men pay it for a season and then stop. I have been paying it since 1981.",
      ],
    },
    { type: "sectionCard", roman: "VI", heading: "The Three Births", lede: "Three hospital records. Three sets of footprints. Hina's right index fingerprint on every one. The same mother. Three different doors." },
    {
      type: "prose",
      lines: [{ kind: "drop-cap", text: "Each of our three children has a hospital identification record. Mother's right index fingerprint. Infant's left and right footprints. The footprints are tiny. The ink stayed sharp on the cardstock. We kept all three. Hina kept all three. They are in this archive because she did not throw them out. She put them in a folder and the folder traveled with us through the houses." }],
    },
    {
      type: "births",
      label: "A litany",
      entries: [
        { name: "Moaaz Furqan Koshul", date: "December 7, 1990 · 10:56 a.m. · Dr. Fox" },
        { name: "Shahbaaz Koshul", date: "November 26, 1992 · 6:35 p.m. · 8 lbs · 21 inches" },
        { name: "Zanab Koshul", date: "March 25, 1996 · 2:57 a.m. · 7 lbs 11.5 oz · Dr. Fernandez" },
      ],
    },
    {
      type: "prose",
      lines: [
        { kind: "plain", text: "On Shahbaaz's record, at the top of the page, in Hina's handwriting, are two words: HAPPY BIRTHDAY! She wrote it on the hospital form. The form is supposed to be only the medical and identification data. She wrote on it anyway. The exclamation point is hers." },
        { kind: "plain", text: "I want to tell you what those three records together mean to me now. They mean that my wife was on the labor and delivery floor of three different hospital nights at twenty-three, twenty-five, and twenty-nine years old, and on each of those nights she came out of it with a living child and her own life and the will to make a folder for the paperwork. The third one, Zanab, came six weeks after we closed on the flower shop. Hina was nine months pregnant during the closing, two weeks before Valentine's Day. She walked through the financial paperwork and the medical paperwork in the same season. The deeds came home in February. Zanab came home in March." },
        { kind: "plain", text: "I sometimes look at the footprints on those three sheets and think: these three small feet are the reason for the building. Not the reason we bought it — we bought it because the chance came and the brothers said go. The reason the building matters. The shop was the means. The children were the meaning. She knew the difference. She never confused them." },
      ],
    },
    { type: "pullquote", lines: ["Our home is her domain", "in which she is the queen."], src: "A True Wife · 1991" },
    { type: "sectionCard", roman: "VII", heading: "September 1992 · The Parking Lot", lede: "Hina was seven months pregnant with our second son. A car was waiting for us at 17 West Englewood Avenue, Apt 402, when we pulled in one evening. My mother was in it. My sister and her husband. My brother and his wife. They had left my father and the house, and they had nowhere else to go that night." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "We pulled into the lot at 17 West Englewood Avenue in Teaneck one evening in September 1992. Apartment 402. Hina was seven months pregnant with Shahbaaz. Moaaz was twenty-one months old, asleep in the car seat. The car already in the lot, parked and waiting for us, had my mother in it. My sister and her husband. My brother and his wife. They had left my father and the house that day. They had nowhere else to go that night. So they came to where we were." },
        { kind: "plain", text: "I want you to picture the apartment they were about to walk into. One bedroom. The bedroom was ours. A small living room. A small kitchen. A small bathroom. A crib for Moaaz against one wall and a hand-me-down dresser against another. There was no spare room. There was no guest setup. There was a couch, a floor, a small dining table that could fit four people if two of them did not mind eating with their elbows pressed in. That was the inventory. That was what we had to offer." },
        { kind: "plain", text: "Hina got out of the car." },
        { kind: "plain", text: "She walked over. She said salaam. She said come up. She was seven months pregnant with the boy whose footprints I have just shown you on the previous pages, and she walked them up to a one-bedroom apartment on the fourth floor that already held one twenty-one-month-old and a husband making six dollars an hour. Five adults from my side of the family, plus the two of us, plus Moaaz, plus the boy still being formed inside her. Eight people in a one-bedroom for the night, and then for the night after that, and then for the weeks after that. They stayed three months. Then I got them an apartment one floor down, on the third floor of the same building. They stayed there six more months. Nine months total." },
        { kind: "plain", text: "I want you to sit with what it costs a woman to do that." },
        { kind: "plain", text: "Not the laundry and the cooking. Those costs are real but they are not the cost. The cost is the privacy of the home that was the only home she had ever shared with a husband who was hers. The bedroom door that was no longer a door at the end of a long day; it was a sound boundary, no more. The kitchen that became a kitchen for five extra people who had their own opinions about how chai should be made. The small living room where the television was, where she had been sitting with our toddler on her belly across the second pregnancy, watching nothing in particular — that room belonged to the five of them now in the evenings. The bathroom in rotation. The mornings audible to everyone. Seven months pregnant and ankles swelling and tired in the bone-tired way of the late second trimester, and instead of putting her feet up in her own living room, she was pouring tea for her mother-in-law who had not blessed her marriage three years earlier." },
        { kind: "plain", text: "It is not easy for a woman to open her home in any circumstance. Whatever the size of the home, whatever the temperature of the people coming in, the opening costs her something. The home is the one place in the world a wife and mother gets to set the terms of. She decides what comes in. She decides what does not. She decides who eats off her plates. She decides what music plays in the morning. When the door opens for guests, those terms loosen. When the door opens for guests who carry a history with the husband — guests who were not there at the wedding, guests who had questioned the marriage, guests whose absence had been the receipt — the terms loosen and they also bend. The home stops being the place where she sets the terms and becomes a place where she manages other people's needs while pretending not to be tired." },
        { kind: "plain", text: "Now layer the specifics. Seven months pregnant. A toddler in the next breath of her, demanding her hands. A husband who is twenty years old and making six dollars an hour and not yet the man who would learn to manage these rooms well. Five adults from a side of the family that had stayed away from her nikahnama at 89 Franklin Road three years earlier. Whose absence then had been the entire receipt of where they stood. Now needing what she had." },
        { kind: "plain", text: "I want you to stop reading for a moment and let me say something larger, because the 1992 incident is one node of a thing I want you to understand about how life is actually navigated and how I have tried to navigate it." },
        { kind: "plain", text: "The world is full of moves. My mother made moves in our living room that fall, and the moves were one kind. But the moves do not stop in living rooms. Marketing makes moves on you every day of your life. Politics rewrites history in front of you and asks you not to notice. Whitewashing rolls over inconvenient facts. Propaganda dresses itself up as common sense. Colonial lenses tell you what to admire and what to ignore. Gender lenses tell you what a woman is for and what a man is for, and most of what they tell you is wrong. Family politics — in every family, in every culture — runs on the unspoken obligation, the position, the bit of pressure applied at the right angle. Bahishti Zewar tells you one set of things; the West tells you a different set; both have moves embedded in them, and somewhere underneath both is the actual life Allah is asking you to live. The world arrives every morning with a hundred small attempts to get a move past you. Some of them are loving. Most of them are commercial. A few of them are designed to do you harm." },
        { kind: "plain", text: "The work of an adult, as I have understood it — and I have not always done this work well — is to see the moves. Not to refuse to engage with the world because the world has moves. Not to live in suspicion, treating every gesture as a threat. But to see beneath the surface of what is being said and what is being offered, and to ask: what is the underlying thing here? What is actually being asked of me? What is being smuggled in alongside the request? What history is doing its quiet work behind this gesture? What position is this person speaking from? What is the real cost, to me and to mine, of saying yes here, and what is the real cost of saying no?" },
        { kind: "plain", text: "I have been doing this kind of looking since I was a child. Not because I chose to. Because something in me could not do otherwise. I was the kid who could not take a sentence at face value. I was the kid who heard what was underneath. The cost of being that kid — and then that adolescent, and then that young man, and now this fifty-four-year-old at a screen — has been considerable. Most of the trouble I have had in my life has come from refusing to wave things past. I have paid in years for things I saw clearly and could not unsee. I will not pretend the price has been small." },
        { kind: "plain", text: "But the work itself is not optional. It is what an adult does. The Quran says the first thing Allah taught Adam was the names of things, and naming is the beginning of seeing, and seeing is the beginning of every kind of decent action. If you cannot see, you cannot help. If you cannot name, you cannot protect. If you wave the moves past because the moves are uncomfortable to look at, you become a participant in whatever the moves were doing." },
        { kind: "plain", text: "What seeing is not, though — and this is the second half of the lesson, and the half I want you to hold onto — is fighting." },
        { kind: "plain", text: "Seeing the moves does not mean drawing a sword every time a move appears. It does not mean turning every encounter into a battle to be won. It does not mean making your mother into an enemy because she came to your apartment with five people and used the tools she had to use the way she had been raised to use them. It does not mean making your in-laws into enemies because they have their own politics. It does not mean making the world into an enemy because the world has marketing in it. That posture — constant battle, last stand at every door — is not the posture of the adult. It is the posture of someone who has seen the moves and panicked, and the panic has eaten the wisdom." },
        { kind: "plain", text: "What seeing is, when it is doing its full work, is this: you see the move, you understand what it is and where it comes from, you decide what to do about it, and most of the time what you decide to do is something quieter than a fight. You bend without abandoning. You absorb what you can bear to absorb, because absorbing it is the thing that allows the relationship to keep going, and the relationship is more important than the score on this particular evening. You preserve the dignities of the people involved — including your own, including theirs, including the dignity of the people who would be harmed if you blew the whole thing up. You stand for what is right, but you stand for it as gently as the circumstances allow. You sacrifice some ground in this moment because you can see that holding it would cost more than giving it up. You help the relationship evolve by not making it die over this. You help life move forward by not insisting that every battle be the last battle." },
        { kind: "plain", text: "You also do not lie. You do not pretend the move did not happen. You see it, you name it inside yourself, you may name it to the person if naming it would help, you may name it later in a letter, you may name it twenty-three years later in a household theology email to your children that begins I think it should be made clear. Naming has many timings. The timing matters. The act of naming, eventually, somewhere, in some form, is not optional — because the alternative is letting the move become the truth, which is how lies become the air a family breathes. But the timing of naming is itself a piece of wisdom. You name when naming will do good. You wait when waiting will do better." },
        { kind: "plain", text: "The principles do not abandon themselves under this. They bend. A principle that cannot bend in a parking lot in September of 1992 is not a principle — it is a posture. The principle that the door opens for a human being in need is a principle Hina held that evening, and she held it without abandoning the principle that her marriage was hers and her home was hers and her dignity was hers. She bent the second set of principles to honor the first. She did not abandon either. The bending was the wisdom." },
        { kind: "plain", text: "I want to say something here that the kids should hear plainly, because if I let the prose stay polite about it the meaning will get lost." },
        { kind: "plain", text: "What I have just described — seeing without fighting, bending without abandoning, choosing the slow inch forward over the loud last stand — is not something I learned. It is what I came in with. It is my fitra. I was born this way. I was the boy at nine who gave a heart pendant to a girl of fourteen. I was the boy at twelve who refused to attend a wedding because the wedding was wrong. I was the boy at fifteen who walked to an empty field rather than swing back at a world that was swinging at him. The gentleness, the self-sacrifice, the not-seeing-things-in-black-and-white, the carrying of more than my share, the willingness to absorb what could be absorbed so that the larger thing could keep going — that is who I am. It is who I have been since I had words. I did not invent it. I did not earn it. Allah gave me the disposition Allah wanted me to have, and the disposition is gentle by default and furious only when something I love is being harmed." },
        { kind: "plain", text: "What I want you to understand is the direction of influence in this marriage on this particular axis. Your mother had her own gentleness, her own grace, her own willingness to forgive. She had also worked out her own theology by the time we married — the theological clarity in her was hers, born of her own seeing, sharpened by what she had survived at fifteen and sixteen. She was a moral force in her own right, and her seeing was sharp before I ever met her again as an adult. None of what was hers came from me." },
        { kind: "plain", text: "But the particular practice of the gentleness — the willingness to hold theology gently in a room where the room was being difficult, the patience to let things pass when letting them pass would help, the choice to give grace to people who had not earned it — that practice in its full daily form lived stronger in me than in her. It was my fitra in a way that was inherited from no one I can name, just given by Allah, and Hina knew it when she saw it. She had the disposition for it too. But the deployment of it in the difficult rooms came more easily to me. Over the years she watched it and absorbed some of it. She softened where she had been sharper. She forgave where she might have held the line. She would tell me, in letters you can read in her own hand a few pages back, that I gave her peace and serenity, comfort, support and strength, that the need of goodness in her was filled by me, that the decency was what she had married. Those are her words. She wrote them down because she meant them." },
        { kind: "plain", text: "I had my share of her gifts too. The theological seeing, the sharpness about what was actually happening underneath, the moral clarity that would not bend — those things lived in me as well, and they were strengthened by being around her. We sharpened each other. The marriage was the meeting of two people who each carried more of one register and both shared in the other. I was the one who held the gentle posture more naturally in the room. She was the one who held the theological frame more naturally in language. Each gave the other more of what the other carried less of. That is how marriages between people who actually love each other work." },
        { kind: "plain", text: "I am saying this carefully because I do not want the kids to flatten either of us. Your mother was not a theologian who needed me to teach her how to be gentle. She was a complete human being with a full inheritance of her own. What I gave her was more of the daily practice of gentleness toward people who had not earned it — in particular, in the years after we married, in the rooms where her own family or mine made the practice difficult. What she gave me was a sharper theological language for what I had been doing by instinct all along. We were equals in the marriage. The currents of influence ran in both directions. They were not symmetrical — on this particular axis, the current ran more strongly from me to her than the other way — but they ran both ways. Both ways are true." },
        { kind: "plain", text: "The other thing I want you to know — because the same letter on my desk that names what she loved me for is the letter where the friction also lived — is that the gentleness that drew your mother to me was also the gentleness that pissed her off at times. The same posture she fell in love with was the posture she sometimes could not bear that I was holding. When she saw me let something pass that she would not have let pass on her own terms, she was furious. Not at the world. At me. She had wanted me to fight harder in certain rooms. She had wanted me to draw a harder line. The gentleness she loved when it was bent toward her was harder for her to love when it was bent toward people who, in her judgment, had not earned it. That tension lived inside our marriage for thirty years. It lived inside the apartment in 1992 with my mother and the five who came with her. It would live inside the apartment again in 2014 when she wrote me letters about how I let things go that should not have been let go. The gentleness was the thing she had married. The gentleness was also the thing she sometimes raged at across the kitchen table." },
        { kind: "plain", text: "Both were honest reactions to the same disposition. I held them both as honest then. I hold them both as honest now. The work, as I have understood it, is to be who Allah made me to be and to not abandon that disposition because someone I love wishes I would be slightly different. The work is also to hear what the one I love is telling me about where the disposition is failing them and to do better where I can do better, without becoming a different person to be more pleasing. Hina did not want a different person. She wanted me. She just wanted me to be more vigilant in certain rooms about who I was being gentle toward. That was fair. That was true. I tried. I did not always succeed." },
        { kind: "plain", text: "What it gave me in that apartment in 1992 was this. I saw what my mother was doing. I had been seeing her since I was a child. I did not get fooled. I also did not turn the apartment into a battlefield. Where I could intercept a move before it reached Hina, I intercepted it. Where I could absorb a cost myself so that Hina would not have to absorb it, I absorbed it. Where I had to let something pass because letting it pass would let the larger thing keep going, I let it pass — and I named it to myself, and sometimes I named it to Hina later when the door was closed, and we kept moving. I was not a perfect filter. I missed nights. I let pass what I should not have let pass. Hina would write about some of those nights in letters that came twenty-three years later. The letters are not in this chapter. But the receipts they carried began in this apartment, and they began in part because the filter was imperfect, and they began in part because the disposition is the disposition and the disposition has costs as well as gifts." },
        { kind: "plain", text: "The deeper pushing-and-taking of our life together — the wider Beg family ever-present, the staff at the shops, the businesses themselves which always wanted more, the demands of the community, the demands of life in general — that was a different and longer story, and the book will tell it in its own chapters. This evening in 1992 was one specific incident with my mother and the people she came with. I have named it the way I have named it because the kids reading should see what an actual incident looks like up close, and what working it through, gently, while seeing the moves, actually requires of the people in the room." },
        { kind: "plain", text: "Which leaves the question that the whole chapter has been circling. Why did Hina open the door? Why did she pour the tea? Why did she carry the second pregnancy through nine months of a one-bedroom apartment that was no longer her own?" },
        { kind: "plain", text: "Not because she had to. Not because a law of the house required it. Hina did not absorb the cost out of duty to my mother or to me or to the marriage as a contract. She absorbed it because of what she understood about life itself." },
        { kind: "plain", text: "She understood that she was inside something larger than the room. The universe. The bigger world Allah had made. The higher human values that have to be alive in someone or they are not alive anywhere. She understood that what we had — the life, the marriage, the toddler, the second child being formed, the small apartment, the six dollars an hour, the parents who were still living, the health, the eyes that could see, the bones that could carry weight up four flights of stairs — was given to us. We had not earned any of it. We were not entitled to any of it. We had been blessed with all of it, and the response to being blessed is not to ration the blessing back to people based on whether they had earned it from us. The response to being blessed is gratitude, and the operating practice of gratitude is to give what was given to us, because nobody had earned it from anyone in the first place." },
        { kind: "plain", text: "That is the theology of the door opening that evening in September 1992. Not I owe my mother-in-law. Not this is what wives do. Not this is what the marriage demands. But I have been blessed with a roof and a husband and a son in my arms and another being formed inside me, and these five people in the parking lot are also human beings with souls Allah made, and the decency life demands of me when I have a roof and they do not is to open the door." },
        { kind: "plain", text: "Hina also did it because of who she was choosing to be. Not just for that night. For the long arc. She had decided early what kind of mother she wanted to be. What kind of wife. What kind of human being. She had decided that whatever life dealt — and life had already dealt her quite a bit by twenty-five — she was going to be a person who answered with grace. Not because anyone had earned the grace from her. Because grace was the answer life demanded of her, given everything else she had been given. She wanted our children to grow up watching that answer. She wanted them to be people who, when they were tested, answered better than they had been treated. Despite all of it. Despite everything. Be thankful. Be graceful. Not because anyone earned it. Because that is what is asked of us, in this life, when we have been given as much as we have been given." },
        { kind: "plain", text: "This is the woman who carried Shahbaaz through that fall and gave birth to him on November 26, 1992, weighing eight pounds and stretching twenty-one inches, the boy whose hospital record has her right index fingerprint at the top and the words HAPPY BIRTHDAY! in her own writing, exclamation point and all, on a form that was supposed to be only medical data. That writing was hers because the gratitude was hers. The exclamation point was hers because the joy was hers. She had spent the months of his being formed inside her pouring tea for five adults from a side of the family that had stayed away from her nikahnama, and at the end of it she wrote HAPPY BIRTHDAY! on a hospital form and meant every letter of it." },
        { kind: "plain", text: "That is who your mother was in September of 1992. I want you to know it. I want you to know it not because she would have wanted credit for it — she would not have — but because the way she lived is the way I want you to understand what is actually being asked of you in this life when life has been good to you." },
        { kind: "plain", text: "She did things right. That is what I want you to know. She did them right in 1992. She did them right for the next twenty-seven years. And I did things right too — but not as right as her." },
      ],
    },
    {
      type: "poem",
      title: "Did You Ever See Me Abandoning",
      translit: "Ahmad · 2026 · written while this chapter was being written",
      stanzas: [
        { lines: ["Even though it's all maddening", "did you ever see me abandoning?"] },
        { lines: ["What you saw was me handling.", "Carrying. Standing. Quietly channeling."] },
        { lines: ["Principles planted in pain — still practicing.", "Faith under pressure — still fastening."] },
        { lines: ["While others were counting the endings", "I am still counting the blessings descending."] },
        { lines: ["Mother's duas still surrounding.", "Father's principles still resounding.", "But mercy inside kept whispering."] },
        { lines: ["Even though it's been maddening,", "all the abandoning,", "truth in my chest still trembling,", "faith isn't dying — just wrestling,", "and even if life keeps unraveling", "my heart keeps circling and traveling."] },
        { lines: ["For others it may be the endings.", "The name in my bones still traveling,", "kept circling family like planets do gravity,", "held onto honor through chaos and tragedy."] },
        { lines: ["Fathers stay sacrificing.", "Sons remain shuffling."] },
      ],
    },
    { type: "sectionCard", roman: "VIII", heading: "November 10, 1999 · Promises Kept", lede: "Tenth wedding anniversary. The first night I had spent away from my children since I had become their father. The thank-you note I wrote to my mother-in-law afterward." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "Ten years to the day after the nikah at 89 Franklin Road, on Wednesday, November 10, 1999, Hina and I went away for one night together. Auntie Beg watched the children. Moaaz was about to turn nine. Shahbaaz was about to turn seven. Zanab was three. It was the first night Hina and I had spent alone since Moaaz had been born." },
        { kind: "plain", text: "I want you to read that sentence again. The first night alone in ten years. People assume parents like that have not figured out how to leave. The truth is more particular. We had been told to leave plenty of times. Auntie Beg, on a few occasions in those years, had said the equivalent of go, go — you two should go to the movies, I have the kids, go. We would get in the car. We would drive to the theater. We would sit in the parking lot. We would not be able to bring ourselves to buy the tickets. We would drive back home." },
        { kind: "plain", text: "Sometimes we made it as far as a restaurant. The restaurants in our area in those years were not very good. There was no excitement to dinner anyway. We would eat fast and head back to the kids. We did not understand how other parents did it. We watched other couples leaving their children with grandparents and we said the things parents say to each other in those situations — good for them, that's nice, glad they can do that — and then we drove back to the den, where the kids were, and watched them sleep, and felt right." },
        { kind: "plain", text: "I have written elsewhere about the principle of promises kept. There is a poem of mine that lives near the line. The first thing a young marriage with three small children owes itself is that the children will not be alone. We kept that so completely for ten years that we could not figure out how to break it for an evening. The inability to leave was not a failure of imagination. It was a feature of the marriage. What we had said in the living room in 1989 was working." },
        { kind: "plain", text: "What changed in November 1999 was that Auntie Beg had set it up in advance, told us a date, told us a time, taken the kids, locked the door behind us, and made it impossible to drive back. Even then we were uneasy. We went anyway. We had a quiet night. We came back. A few days later I sat down at the typewriter and wrote her a thank-you note." },
      ],
    },
    {
      type: "essayDrop",
      label: "Letter to Auntie Beg · typewritten · signed by hand",
      title: "To my mother-in-law",
      byline: "Wednesday, November 10, 1999 · tenth wedding anniversary",
      paragraphs: [
        "ASSALAMOLAIKUM",
        "Dear Auntie Beg,",
        "I wanted to thank you for watching the kids on Wednesday, Nov 10th, 1999. I know that you have watched them plenty of times before: on holidays and on Mondays — so that Hina could come to work. I appreciate those times, as well.",
        "However, this last time was for a different reason and that's what makes it special, insha-allah something we will remember for a long time to come. It was the first time in 10 yrs in which, I was able to go away for a night with my wife. It was very nice and I wanted to let you know how much I appreciated it. We had a nice time — even though we are not use to being alone — without our children. For one night it was a nice change. I wanted you to know that even though it is a few days later, I haven't forgotten and I wanted to express my gratitude and thanks for enabling me to spend a few moments with my wife and putting a smile on her face.",
        "Auntie you are a very thoughtful and considerate person and I am glad to have a woman like yourself as a mother-in-law.",
        "Thank You.",
        "With Sincere Appreciation,",
        "Ahmad-Abrar",
      ],
    },
    {
      type: "prose",
      lines: [
        { kind: "plain", text: "Twelve years before this letter, in 1987, Auntie Beg's husband had written me a letter telling me to leave his daughter's life. He had been right to write it, given what he knew. I had been the right person to receive it, given what I was at fifteen. We had both been telling the truth as we understood it." },
        { kind: "plain", text: "By 1999 her father had blessed the marriage with his presence and his prayers. By 1999 her mother was watching our three children so we could go away one night. By 1999 the man who had been called haram by her father was signing letters to her mother as Ahmad-Abrar, the same merged signature he had first used in 1991, two names with a hyphen between them. The hyphen was holding." },
        { kind: "plain", text: "Auntie Beg's specific gift, in the letter, is named: on Mondays — so that Hina could come to work. She was, on every Monday for years, the reason Hina was able to be at the shop. The flower shop did not run on Hina alone. It ran on Hina plus the woman who was her mother. The shop survived in part because the older generation kept showing up to mind the children." },
      ],
    },
    { type: "pullquote", lines: ["She is the girl I grew up with,", "she is the lady I love.", "She is the woman who is now,", "my wife."], src: "A True Wife · the line that survives" },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "By the close of the nineties we had what we had wanted, more or less. A shop on Teaneck Road that bore our names on the deed. Three children whose footprints we had kept in folders. A house on Park Avenue in Teaneck that we had bought in March 1997 and have lived in ever since. A marriage that had been tested and held. A community that watched us with the mixture of pride and resentment communities reserve for couples who do not give them anything to gossip about." },
        { kind: "plain", text: "The shop was ordinary. Flowers came in on Tuesdays. Weddings in the spring. Mother's Day in May. Funerals every week. Valentine's Day was the engine of the year. We worked the holidays. We watched the kids. We drove past the theater on the rare nights we tried to go out and could not bring ourselves to buy the tickets. We came home. We slept in the same bed." },
        { kind: "plain", text: "The ordinariness is the point of this chapter. After everything in the previous chapters — her first marriage, the homelessness, the lawsuit, the splintering, the living-room nikah at 89 Franklin Road — we got the ordinary years. The ten years of nobody-watching, of show-up-on-Monday, of make-the-billing-make-sense, of teach-the-children-the-words, of keeping the contract. The angels who had kept the record at the wedding kept the record through the ordinary years too. The ordinary years are not less holy. They are where the contract gets kept." },
      ],
    },
    {
      type: "duaCard",
      label: "A du'a · for the keeping",
      arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ",
      translit: "Yā Muqallibal-qulūb, thabbit qalbī ʿalā dīnik.",
      meaning: "O Turner of hearts, keep my heart firm on Your religion.",
      gloss: "My father-in-law had said this du'a through the splintering. I said it through the ordinary years. A keeping, said over and over until it becomes the shape of a life.",
    },
    { type: "prose", lines: [{ kind: "plain", text: "Then came September 2001. That is the next chapter." }] },
    {
      type: "artifactRow",
      rowLabel: "August 1991, in his hand at twenty",
      heading: "A True Wife — the four-page essay",
      intro: "Two years into the marriage. A son who was eight months old. The young husband sitting down to write what a wife is, what a marriage is, what he intended to be inside of it. The essay survives.",
      items: [
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811226/buyahka-abrar/drive-docs/1ADhtMvENkfZ-dWIDwQu9f4VRxaSSgX3X.jpg", alt: "A True Wife essay, page 1 of 4", caption: "Page 1 of 4. Dated August 13, 1991." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811257/buyahka-abrar/drive-docs/1iMvs1IdUwR_A8ShKJeM-fhnse3EOC4G_.jpg", alt: "A True Wife essay, page 2 of 4", caption: "Page 2 of 4." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811285/buyahka-abrar/drive-docs/1Ra2rUkivqmf_3GTdX_PryOW0tYfXNW7R.jpg", alt: "A True Wife essay, page 3 of 4", caption: "Page 3 of 4." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811229/buyahka-abrar/drive-docs/1AtLyS9aQabrkNfsCXqQPK1D-OUD4iQv7.jpg", alt: "A True Wife essay, page 4 of 4", caption: "Page 4 of 4. \"My true wife — her name is Hina.\"" },
      ],
    },
    {
      type: "artifactRow",
      rowLabel: "Letters Across the Marriage",
      heading: "What survived in his hand and hers",
      items: [
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811318/buyahka-abrar/drive-docs/1Y6PrvR6LbkE0DeoM8kCvqJbflV3fj-z2.jpg", alt: "Ahmad's 2-page letter to Hina, 1991, page 1", caption: "The second 1991 letter. Page 1 of 2. A shorter letter; a more direct register than the Khabaa five-pager." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811310/buyahka-abrar/drive-docs/1XdC7b3AqsXOfzmsUBv95hN33cH1__TKm.jpg", alt: "Ahmad's 2-page letter to Hina, 1991, page 2", caption: "Page 2 of 2." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811275/buyahka-abrar/drive-docs/1nlKItkwLPBVTWvHWcyNYwF-m9Xwre9MZ.jpg", alt: "Her Fire, full poem", caption: "\"Her Fire\" — the closing line: \"I will, I can, I do, because I think of you — therefore I am, 'The Kid' now 'Your Man'.\"" },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811276/buyahka-abrar/drive-docs/1nMV39dW_sZE39IP9tN-L4zJsPBDlEfPr.jpg", alt: "There is No Abrar without Hina, the inversion essay", caption: "\"There is No Abrar without Hina.\" Ahmad's own hand: \"Without Hina there is no Abrar. Without Abrar there is no Hina... She saved me. I saved her. I truly do not think it was one more than the other.\"" },
      ],
    },
    {
      type: "artifactRow",
      rowLabel: "The Shop and the House",
      heading: "What 1990–2000 looked like",
      items: [
        { imageSrc: "https://drive.google.com/thumbnail?id=1Zl7iK4P2zCSCzyXV9-oyzIYe-MjsqK9s&sz=w1200", alt: "Teaneck Flower Shop", caption: "Teaneck Flower Shop. The shop she walked into in 1986 as a teenager and walked out of in her early thirties as the woman who had built a household, three children, and the early years of the long marriage on this floor." },
        { imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811312/buyahka-abrar/drive-docs/1xf27HfbTdAwj9MDZk0XNkAfUGFBLorH_.jpg", alt: "Ahmad and Hina at the flower shop", caption: "Ahmad and Hina at the flower shop. The early years of the marriage and the business in the same frame." },
        { imageSrc: "https://drive.google.com/thumbnail?id=1Dl-D0SvBkut0OrAl9QXXxvOG-zp7qjIL&sz=w1200", alt: "The young family", caption: "The young family." },
        { imageSrc: "https://drive.google.com/thumbnail?id=1yWeMAorynh-pRhhZ2OYfSRU5Z9xfUcrJ&sz=w1200", alt: "Ahmad with the boys", caption: "Ahmad with the boys. Moaaz and Shahbaaz." },
        { imageSrc: "https://drive.google.com/thumbnail?id=1Sfnim4G5yCMbbJ4rf1OklPR0axDEW1k4&sz=w1200", alt: "Look, a baby brother", caption: "\"Look — a baby brother.\"" },
        { imageSrc: "https://drive.google.com/thumbnail?id=1M3nMF86DehHN7t6VmgxwP63X_CwcrSA5&sz=w1200", alt: "Moaaz and Hina", caption: "Moaaz and Hina. Mother and son." },
      ],
    },
    { type: "chapterEnd", nextTitle: "Chapter Six — September's Children" },
    { type: "fpImage", eyebrow: "1990s · Inside the flower shop", image: img("01_image"), alt: "The shop they built together. Vases behind. Both faces lit.", caption: "The shop they built together. Vases behind. Both faces lit." },
    { type: "fpImage", eyebrow: "Ahmad to Hina · \"I would be everything\"", image: img("02_image"), alt: "A Valentine. Written by Ahmad, to Hina.", caption: "A Valentine. Written by Ahmad, to Hina." },
  ],
};

export default chapter05;
