import type { MemoirChapterContent } from "@/lib/memoirBlocks";

// Transcribed verbatim from leg/chapter_03.html (the package Ahmad approved).
const chapter03: MemoirChapterContent = {
  number: 3,
  slug: "chapter-3",
  title: "The House of Reform",
  soundtrack: {
    name: "Chapter 3 — Hina Emerges",
    tracks: [
      { media: { publicId: "buyahka-abrar/chapter-03/02_audio", resourceType: "video" }, title: "Joyce Sims — Come Into My Life" },
      { media: { publicId: "buyahka-abrar/chapter-03/03_audio", resourceType: "video" }, title: "Coke Studio — Hina Ki Khushbu" },
    ],
  },
  blocks: [
    {
      type: "hero",
      book: "Buyahka and Abrar",
      chLabel: "Chapter Three",
      title: "The House of Reform",
      em: "Dar ul Islah, the Two Patriarchs, and the Boy They Caught",
      subtitle: "A masjid built by two men from a soccer field in Jalandhar. The boy who fell out of the world they built. The young woman who caught him.",
      meta: "Part I — Inheriting",
    },
    {
      type: "poem",
      title: "Surah al-Ra'd",
      translit: "The Thunder · 13:11",
      arabic: "إِنَّ ٱللَّهَ لَا يُغَيِّرُ مَا بِقَوْمٍ حَتَّىٰ يُغَيِّرُوا۟ مَا بِأَنفُسِهِمْ",
      stanzas: [
        { lines: ["Inna Allāha lā yughayyiru mā bi-qawmin", "ḥattā yughayyirū mā bi-anfusihim."] },
        { lines: ["Allah does not change the condition of a people", "until they change what is within themselves."] },
      ],
    },
    {
      type: "prose",
      lines: [
        { kind: "opener", text: "What follows is not my story. I was a child on the periphery of it, but I was ever present for it. The men who built this thing are not the men I am writing about in this book. They built the place inside which the rest of this book happens. I owe them the truth of what I saw — and I owe them the discipline not to claim more than what I saw." },
        { kind: "drop-cap", text: "Some of them are still alive. Some have passed. The ones who remain are old men now. The ones who were young men when I was a boy at their elbows would not recognize me on the street. That is the nature of children at the edges of a community. You see everything. You are seen by no one in particular. You inherit the work of men who do not know they are teaching you anything." },
        { kind: "plain", text: "This chapter is for them. And for the boy who fell out of the world they built, and for the young woman who caught him." },
      ],
    },
    { type: "sectionCard", roman: "I", heading: "Two Boys on a Soccer Field", lede: "Jalandhar, before there was a Pakistan. Brooklyn, decades after the world they knew had ended." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "In 1947, on a soccer field in Jalandhar, two boys ran toward the same ball. One was Muhammad Ikram. The other was Khalid Beg. They were eleven, twelve. They were friends the way boys who play together every afternoon are friends, without ever having to name it." },
        { kind: "plain", text: "That summer the partition came. Trains left the cities packed and arrived empty. A million died. Both families lost much of themselves on the road south. Both boys survived. Neither saw Jalandhar again." },
        { kind: "plain", text: "For thirty years, they did not see each other." },
        { kind: "plain", text: "Immigrants do a thing the country they have come to does not always notice. They search. They sit at each other's tables on Friday evenings and ask, where are you from, what part of Pakistan, what village, what school, who do you know — and through the asking, families that were torn apart by the partition try to find the threads of themselves again. Maybe it is a habit. Maybe it is grief that never stopped looking. Either way, the men kept asking." },
        { kind: "plain", text: "It was through those conversations, in someone's living room in Brooklyn or Queens, that my father first heard the name Khalid Beg again. Dr. Beg was already in the country. The two men eventually met — at the masjid where my father's family had come to live on the second floor while the prayers happened on the first. They talked the way men who have not seen each other in thirty years talk. Through Dr. Beg, my father learned about Teaneck. A few months later, the family moved." },
        { kind: "plain", text: "Two boys from a soccer field in Punjab built a mosque together in New Jersey. The mosque they built is the inheritance this chapter is about." },
      ],
    },
    {
      type: "artifactCard",
      label: "Artifact · The Bloodline",
      heading: "Beg Family Tree, in Khalid Beg's Records",
      imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811206/buyahka-abrar/drive-docs/1_r-rIY-dDZmmCcdMUgE_E0wf5EgPSeLr.png",
      alt: "Beg Family Tree, scanned from Khalid Beg's papers",
      caption: "The family tree Khalid Beg kept among his papers. Jalandhar before partition. Hamilton, Ontario. Then New Jersey. The line that walked away from the soccer field in 1947 and walked back to it, through three countries and forty-two years, on November 10, 1989.",
    },
    {
      type: "pullquote",
      lines: ["Two boys from a city they could no longer go home to.", "And then — my father's son married Khalid's daughter.", "Their bloodlines, broken open in 1947,", "came back together."],
      src: "on the patriarchs",
    },
    { type: "sectionCard", roman: "II", heading: "Uncle Nader's Garage", lede: "Before there was a building. Before there was a sign. The cooing of pigeons through the wall during khutbah." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "Before there was a building, there was a garage on Copley Avenue in Teaneck." },
        { kind: "plain", text: "The boy is eight. Maybe nine. His father has packed him and his brothers into the car on a Friday afternoon, and they have driven the few blocks to a house belonging to a man called Uncle Nader. The garage door is open. Rugs have been laid down on the concrete floor. The smell of motor oil has not left the room. Underneath the smell of motor oil is the smell of attar from the bottles the men have brought, and underneath that, the warm bread smell of the neighbor's kitchen drifting through the open windows." },
        { kind: "plain", text: "In the backyard there is a pigeon coop. The boy can hear the pigeons cooing through the walls of the garage all through the khutbah. Uncle Nader is a soft-hearted man with a Trinidadian accent — the kind of voice that people from the islands carry with them, smooth and warm, the kind of voice that makes you feel at home in a garage that smells like motor oil. The boy will remember the cooing of the pigeons before he remembers what the imam said." },
        { kind: "plain", text: "A handful of families. Eight or ten men. Their wives in another part of the house. Children threading between adult legs to find each other. Someone calls the iqamah. The men line up. The boy takes his place at the back, between his father's hand and his brother Assad's elbow." },
        { kind: "plain", text: "This is the first place he ever heard the word community used about people he could see." },
        { kind: "plain", text: "The garage will not last. Uncle Nader will move out of the area within a year or two. Other families will offer their houses temporarily. Someone's basement. Someone else's living room. The prayers will keep happening because the prayers do not need a building. But the men who are now coming together every Friday have started to look at each other and ask whether they could build something more permanent." },
        { kind: "plain", text: "My father is not the kind of man who lets a thought go once it has entered him. He starts doing the work in the shadows. Not in the meetings, not at the front, but in the phone calls, in the conversations with the brothers and uncles, in the moving and the asking and the small acts of getting things ready for the men who will be in the forefront." },
        { kind: "plain", text: "The boy only knows that his father keeps having long phone calls in the evenings, and that more men are starting to come to the house, and that something is being decided in rooms he is not allowed in." },
        { kind: "plain", text: "He will be allowed in soon enough. Once the families had decided to put an offer on the property, the boys — my brothers and I — were taken to see it. From that day forward, we were in the rooms where the discussions happened and the work was being done. The men who moved the chairs around the table were us." },
      ],
    },
    { type: "sectionCard", roman: "III", heading: "The Little Old Lady's Garden", lede: "A small lot. A hut. Neat rows of vegetables behind it. The man with the pen was Khalid Beg. My father was the engine." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "The boy was perhaps ten when his father drove him out one Saturday to look at the lot." },
        { kind: "plain", text: "It was small. A small hut sat on it. Behind the hut, an old woman had a garden — neat rows of vegetables and flowers, the way a woman who has lived alone for a long time keeps her garden. The little old lady met them at the door. She had agreed to sell." },
        { kind: "plain", text: "The men who would buy the property were not Ikram. They were Dr. Khalid Beg and Masoom Jaleel. Dr. Beg signed the first check. Masoom Jaleel was at his side. They were the visible founders. They were the names that would be on the deed, the names that would later be on the imam's nameplate, the names that the New York Times would print in 1991 when the article ran." },
        { kind: "plain", text: "Ikram was in the room — and had been in the room for the meetings that decided to look for property in the first place. He would be in the room for every meeting that followed for the next several years. He had picked up the phone and called the man who knew about this lot. He had driven to look at it before anyone else. He had spoken to his wife at the kitchen table about whether the families could afford what was being asked. But he was not the man with the pen." },
        { kind: "plain", text: "The project itself had been talked about since 1975. The property was purchased in 1979. The building would not be finished until 1985. Ten years from idea to dome. Ten years of phone calls and arguments and weekend drives to see lots that did not work out. My father was in nearly every one of those years." },
        { kind: "plain", text: "This was his pattern." },
        { kind: "plain", text: "In 1977, in the family's first apartment in Queens, his family had been one of the families whose house became the first floor of a mosque — Masjid al-Falah, which still stands and which has become the headquarters of an entire revivalist movement. Ikram had not been the imam there either. He had been the man on the second floor. The engine." },
        { kind: "plain", text: "His wife called him the engine. His children, later in life, would call him the unseen motor. He was the man who quietly bought the house, signed his name on the papers, made the phone calls to the men who would become founders." },
        { kind: "plain", text: "The boy, watching, did not understand at ten that this was rare. He thought all fathers were like this. He thought this was what men did. It would take him another twenty years and his own attempts at building to understand that men who do this are unusual, and that men who do this without bitterness are more unusual still." },
      ],
    },
    { type: "sectionCard", roman: "IV", heading: "What the Wives Built", lede: "The husbands signed the checks. The wives held the people. Between Shagufta and Nusrat, the social fabric of the community was woven." },
    {
      type: "prose",
      lines: [{ kind: "drop-cap", text: "There is a sentence in something the boy will write decades later, as a grown man, in a foreward to a packet of records he wants the next generation to have:" }],
    },
    {
      type: "pullquote",
      lines: ["This was only possible", "with the unwavering support of their wives.", "Who undoubtedly played a major if not majority role", "in pulling the social circles, and thus community, together."],
      src: "Foreward Dar Ul Islah · 2021",
    },
    {
      type: "prose",
      lines: [
        { kind: "plain", text: "He means it as a thank-you. It is also a fact." },
        { kind: "plain", text: "His own mother — Shagufta — was the firecracker. Energy, hospitality, food from scratch at a moment's notice, sharp tongue to keep people in line, big heart to help anyone who came through the door. There was no one like her in the community. When other women came to visit, they came to her kitchen. The kitchen was the room where the actual decisions about how the community functioned were made, even though the men sat in the living room and thought they were the ones deciding." },
        { kind: "plain", text: "Auntie Beg — Nusrat — Hina's mother — held the same role on the other side. She was the gentle one. Where Shagufta pushed, Nusrat held. The women who would not have followed Shagufta would follow Nusrat. The women who would not have followed Nusrat would follow Shagufta. Between them, the social fabric of the community was woven. The husbands signed the checks. The wives held the people." },
        { kind: "plain", text: "The boy does not yet know that this is the pattern of every community that ever survived. He will learn it later. He will learn it slowly, and he will learn it inadequately, because he is a boy. But the women in the kitchen were already teaching him." },
      ],
    },
    { type: "sectionCard", roman: "V", heading: "The Tent, the First Sign, the Uncles", lede: "A catalog of what the boy saw. Wooden arrows painted red and white. A Black American convert's sign on a chain-link fence." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "What follows is the boy's catalog of what he saw." },
        { kind: "plain", text: "He remembers Uncle Tahir and Uncle Masoom picking him and his brothers up every morning for Fajr. Sometimes in a green station wagon. Sometimes in a red firebird. The detail of the cars matters. These were not solemn old men. These were men with cars they loved. The masjid had texture." },
        { kind: "plain", text: "He remembers Uncle Hameedudin throwing the football around with the boys on the property after Fajr was done. The masjid was not only solemnity. There were footballs." },
        { kind: "plain", text: "He remembers Uncle Suri cutting wooden arrows by hand and painting them red and white to point the cars to where they should park. Buyahka before Buyahka had a name. A man building a parking system out of wood and house paint because no one was going to come do it for them." },
        { kind: "plain", text: "He remembers Uncle Bajwa running a small backhoe to move and level the land. The labor." },
        { kind: "plain", text: "He remembers Azmat Rehmat, who was the cool one. Cool cars. Cool clothes. The community had glamour too. Not all uncles. Some young men." },
        { kind: "plain", text: "He remembers the Ramadan tent that went up every year before there was a permanent building. The tent was the masjid in its larval form. A stretched piece of canvas, prayer rugs underneath, and a hundred and fifty people who behaved as if it were a marble courtyard in Damascus. They were practicing." },
        { kind: "plain", text: "He remembers Ajaz saab making huge pots of tea for everyone because someone had to make the tea, and Ajaz saab had decided it would be him." },
        { kind: "plain", text: "He remembers Brother Jess and Brother Osman, two Malaysian students from FDU, taking the boys to the park and on outings, and being the first non-Pakistani Muslims he ever called brother." },
        { kind: "plain", text: "He remembers going with the Catovic family to ISNA conventions and seeing, for the first time, that the Muslim community in America was much bigger than the few families who had become his weekly Friday." },
        { kind: "plain", text: "He remembers the first sign for the masjid." },
        { kind: "plain", text: "It was painted by a man named Mr. Wilbur, the African American art teacher at Longfellow School. Mr. Wilbur was Muslim. He had become Muslim in the way that many Black Americans had become Muslim through the long arc of the twentieth century — through the Nation, through Malcolm, through Imam W.D. Mohammed, through the slow rediscovery of an Islam that had always belonged to them even when the world said otherwise. Mr. Wilbur painted the sign that said Dar-ul-Islah, and it was hung on the chain-link fence that surrounded the property, and it was there for years." },
        { kind: "plain", text: "The boy did not know at ten what it meant that the first public face of a mosque founded by Indo-Pak immigrants was a sign painted by a Black American convert. He would understand it later. He would understand it as the rebuke to every person who has ever told him that Islam is a foreign religion in America. The first sign of the first masjid he ever knew was painted by an American." },
        { kind: "plain", text: "In the same years, on a burnt orange couch a few miles away, the boy was reading Bahishti Zewar. The two facts sit together. Bahishti Zewar was the manual one community had carried with it across the ocean. Mr. Wilbur's sign was a different thing entirely. Both were called Islam. The boy already, at ten, had begun the work of figuring out which one to keep." },
      ],
    },
    { type: "pullquote", lines: ["Tip of the spear —", "the men who put their bodies first", "so the rest could pray under a roof."], src: "on the founders" },
    { type: "sectionCard", roman: "VI", heading: "The Name, the Vote", lede: "House of Reform. They named it after its limitation, not its triumph." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "When the elders sat down to choose a name for the community, they chose Dar ul Islah." },
        { kind: "plain", text: "House of Reform. Abode of Reform. The translation matters. They did not name it Dar ul Iman, House of Faith. They did not name it Dar us Salam, House of Peace. They named it after its limitation, not its triumph. They knew, even as they were buying the property, that the community would need to keep reforming itself. That what they were building was not a finished thing but a workshop." },
        { kind: "plain", text: "The boy did not catch this at the time. He caught it decades later, when he understood that almost no one names a thing after its weakness on purpose. The elders who named Dar ul Islah were either unusually humble or unusually clear-eyed. He thinks now, looking back, that they were both." },
        { kind: "plain", text: "Then came the vote." },
        { kind: "plain", text: "The architects had drawn up two designs. One was a simple structure, something like four hundred thousand dollars to build. The other was an ambitious design — a dome, a minaret, a courtyard — closer to one point two million. The elders argued. They argued in meetings the boy was sometimes allowed into and sometimes was not. They argued in living rooms after dinner. They argued in cars on the way home. Some men felt the simple structure was more Islamic — modest, sufficient, not given to ostentation. Some men felt the larger design was the right thing for the community Bergen County would become — a building that would be visible from the turnpike, that would announce that Muslims belonged here, that would be there for the grandchildren." },
        { kind: "plain", text: "Both positions were sincere. Both positions had Islamic backing. This is what community-building actually looks like — not unity, but disagreement, held inside a shared project." },
        { kind: "plain", text: "The vote went to the larger design. The dome and the minaret were built. The New York Times would write about the building in 1991. The MIT Aga Khan Visual Archive would later photograph it. The seventy-foot minaret would be visible from the New Jersey Turnpike, exactly as the men who voted for it had hoped." },
        { kind: "plain", text: "The boy was a teenager by the time the building was finished in 1985. He remembers walking through it the first time. He remembers thinking that buildings are heavy, and that the men who had built it were tired." },
      ],
    },
    { type: "sectionCard", roman: "VII", heading: "The Splintering", lede: "The men who built Dar ul Islah did not stay together. The case began in 1986. A boy sat in the courtroom and listened." },
    {
      type: "prose",
      lines: [
        { kind: "opener", text: "I am going to tell you something I do not want to tell you. I am going to tell you anyway because the book does not work without it." },
        { kind: "drop-cap", text: "The men who built Dar ul Islah did not stay together. The community split. The split was not theological in the way an outsider might imagine — Sunni against Shia, or this madhhab against that one. It was something more granular and more honest than that. The Indo-Pak subcontinent that produced almost all of these men contains within it twenty or thirty regions, each with its own language, food, customs, and madrasa traditions, and inside each region every gradation from village laborer to aristocrat. There were also disagreements about how a community should fund itself — whether the money should come only from the families inside the room or from overseas backers, and what came with each kind of money — and there were men who had been working since 1975 alongside men who had moved in once the building was going up, each arriving with their own picture of what it should become." },
        { kind: "plain", text: "The split was about whose manner of thinking would guide the masjid forward. That was the truth of it. Not money exactly, not ego exactly, though those were present too. It was about which tradition would set the tone for the next generation. Two groups of sincere men disagreed about that, and the disagreement hardened, and the hardening became a lawsuit, and the lawsuit went to court." },
        { kind: "plain", text: "The groundwork for the case began in 1984. The case itself did not start until 1986. By then I was fourteen, fifteen years old. Old enough to sit in the courtroom. Old enough to understand some of what was being said, though not all." },
        { kind: "plain", text: "My father was a witness. He was on Dr. Beg's side, and on Masoom Jaleel's side, and on the side of the men who had founded the place. He sat where they sat. He testified to what he had seen. The man who had spent his entire adult life staying out of the photograph sat in the front row of a courtroom because, this once, the question being asked was a question he could not stay quiet on." },
        { kind: "plain", text: "The other side had its own good men. I want to be clear about that. They were not villains. Some of them I had loved as uncles. Some of them I still love. They believed what they believed and they had reasons. The case was not about who was a good Muslim and who was not. The case was about who had what right, and who owed what duty, and who could be trusted to hold what." },
        { kind: "plain", text: "A boy sat there and listened." },
        { kind: "plain", text: "I will not tell you what was said. I will tell you what I learned. I learned that building something sacred does not protect you from breaking it. I learned that sincerity is not enough — that two men can both be sincere and still end up on opposite sides of a courtroom, and that the universe does not always sort out who is right. I learned that the same hands that lay a foundation can later sue over the deed. I learned that a community is not a permanent thing. It is a thing that has to be remade every year, every Friday, every time two men disagree and have to choose whether to keep walking the same road or to part." },
      ],
    },
    { type: "pullquote", lines: ["My father and my father-in-law were on the side that lost.", "", "I want you to read that sentence again.", "They lost."], src: "the splintering" },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "The men who had thought about this project since 1975, who had bought the property in 1979, who had held the meetings and made the phone calls and signed the checks and built the building and chosen the name — they lost the case that decided whose vision would guide what they had built. They were told, in effect, by a court of law: the masjid you built is no longer yours to steer." },
        { kind: "plain", text: "What did they do? They did what no one had any right to expect. The next Friday they were at the masjid. They prayed the way they had always prayed, as if no court had ever existed. My father did not raise his voice about it at the dinner table. Dr. Beg did not give a sermon about it from the floor. They lost the case, and for a long time, they kept showing up." },
        { kind: "plain", text: "How long is a long time? A few years. Long enough to model for me what dignity in defeat looks like. Long enough that I would carry the lesson the rest of my life. But the practical truth is harder than the spiritual one. The court did not just take the steering. Over time, the new leadership took the building. The Begs no longer had a masjid that was theirs to use the way a family uses its masjid — for a daughter's wedding, for a grandfather's janazah, for the small private rituals that make a building yours. The next chapter shows you what that meant. Hina's wedding to me, in 1989, was not held in the masjid her father had founded. It was held in his living room. The men who built Dar ul Islah eventually had to bring their own daughters' weddings home." },
        { kind: "plain", text: "I have thought about this for forty years. I do not know how they carried it. I have carried smaller things worse." },
        { kind: "plain", text: "There is a du'a the Prophet, peace be upon him, used to say often, more often than any other du'a according to the narration that has come down to us:" },
      ],
    },
    {
      type: "duaCard",
      label: "A du'a · often repeated",
      arabic: "يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ",
      translit: "Yā Muqallibal-qulūb, thabbit qalbī 'alā dīnik",
      meaning: "O Turner of hearts, keep my heart firm upon Your religion.",
      gloss: "",
    },
    {
      type: "prose",
      lines: [{ kind: "plain", text: "I think my father said this du'a. I do not know that he said it. I never heard him say it out loud. But I think he must have said it. Because to walk back into the same building the week after you have lost the right to shape it, and to pray the way you have always prayed, is to have a heart that has been kept firm by someone other than you. No man does that on his own." }],
    },
    { type: "sectionCard", roman: "VIII", heading: "The Strength of Water", lede: "The work did not stop. It moved." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "When the splintering came, the two patriarchs handled it the way each man had always handled the world. My father kept showing up to Dar ul Islah on occasion. My father-in-law's visits grew less frequent. Both men, in their own way, refused to make a public spectacle of what had happened. The brothers had been brothers since a soccer field in Jalandhar in 1947. They were not going to stop being brothers because of a vote that did not go their way." },
        { kind: "plain", text: "But the work itself did not stop. It moved." },
        { kind: "plain", text: "My father-in-law, Uncle Mirza, Uncle Saleem, Uncle Hamid, Uncle Masoom — these men began the long work of building another masjid. Not in opposition. In continuation. Eid fairs were held without a formal masjid. A meat store was started without a formal masjid. Saut-ul-Furqan Academy — a Qur'an school for the community's children — was started in the rooms above Ludwig's Hardware on Queen Anne Road in Teaneck. They did not have a building yet. They had what they had always had. They began." },
      ],
    },
    { type: "ornament" },
    {
      type: "prose",
      lines: [
        { kind: "center-italic", text: "The strength of water finds a way through things." },
        { kind: "plain", text: "These men had crossed Partition. They had crossed oceans. They had learned new languages in their thirties and forties. They had raised families in apartments and basements while working two jobs. They had built something where nothing existed before, with money they did not really have, by helping and pushing and pulling each other through every obstacle in front of them. To watch a community split was not the first hard thing they had absorbed. It was not going to be the thing that stopped them." },
        { kind: "plain", text: "And I saw all of it." },
        { kind: "plain", text: "As a young man I went with them. Looking for buildings to rent. Looking for property to buy. Loaning the van to pick up materials. Clearing lots. Doing yard work. Making tea. Serving food. The small things a young man can do when older men are doing the larger work. I stayed within earshot of where the decisions were being made and I helped. It is a Koshul trait, handed from father to son. You stay in the room. You move the chairs. You pour the tea. You learn." },
        { kind: "plain", text: "What those men began in the years after the splintering would, over time, become Nida-Ul-Islam, the masjid that still stands. Saut-ul-Furqan still runs as a school. The work continues — all of it initiated by these men. And of course, by their wives. The husbands and the wives who sacrificed for the sake of people they had never met. For the sake of people they would never meet." },
        { kind: "center-italic", text: "And the boy was watching all of it. Until, one day, the boy could not go home." },
      ],
    },
    { type: "sectionCard", roman: "IX", heading: "The Boy in the Entryway", lede: "A blue shalwar kameez. A long overcoat almost reaching her ankles. The most particular thing he had ever seen." },
    {
      type: "prose",
      lines: [
        { kind: "drop-cap", text: "Before there was the dome and the minaret, there was the small hut on the property — the same hut that had stood there when the little old lady had her garden behind it. The community used the hut as the everything-room. Wudu happened there. Tea happened there. The men sat there between salat. The women sometimes used it when the weather drove them in from outside. Children came in and out the way children do, without permission and without notice." },
        { kind: "plain", text: "It was 1981. I was ten, maybe a touch older. I was coming out of the hut and a young woman was coming in. We met in the entryway. We knew each other. Our families had known each other for thirty-four years, since the soccer field in Jalandhar." },
        { kind: "plain", text: "She was Hina. She was older than me by five years." },
        { kind: "plain", text: "I remember saying salam. I remember her radiant self the way she always was. I remember a blue shalwar kameez and earrings that matched the blue, and a long overcoat over the kameez — the kind of overcoat Boy George of Culture Club used to wear, though I would not have known to call it that at the time. I just knew that no one else in the masjid dressed like her, and that no one else in the masjid carried herself like her, and that something about the way she was standing in the doorway with the overcoat almost reaching her ankles was the most particular thing I had ever seen." },
        { kind: "plain", text: "We spoke briefly. I do not remember what we said. I doubt either of us thought, at that moment, that we would one day be married, that we would have three children together, that I would bury her in 2019, that I would write a book in 2026 in which this moment would appear as a hinge. We were two children of the community whose fathers had built the place we were standing in. That was all." },
      ],
    },
    { type: "pullquote", lines: ["The masjid that my father and Dr. Beg", "and Masoom Jaleel and the other families had built", "produced this entryway.", "The entryway produced the meeting."], src: "on the hinge" },
    { type: "sectionCard", roman: "X", heading: "March 1987", lede: "The boy fell out of the world the men had built. The young woman who had walked through the entryway in 1981 caught him." },
    {
      type: "prose",
      lines: [
        { kind: "opener", text: "I want to tell you about the spring after they lost the case. The masjid had a new leadership. The fathers kept showing up. And the boy — the boy who is me, the same boy who watched it all from the back of the room — was no longer at home." },
        { kind: "drop-cap", text: "I will not lay out the inside of my parents' house here. That is not what this chapter is about and the people inside that house are still living. What I will tell you is this: in March 1987, at the age of fifteen, I was no longer welcome under my father's roof. The reasons sit in the territory my sister has her own version of, and that version is true to her in ways I do not need to fight here. I have included her account elsewhere. The fact, on the ground, was simple. I had a duffel bag. I did not have a place." },
        { kind: "plain", text: "Friends of mine had houses that took me in for a night, two nights, three. Their parents fed me. Their parents looked the other way when I slept on a couch that was not theirs to give. I do not have words for what those families did. I have not paid them back. I do not think I can." },
        { kind: "plain", text: "Hina was twenty. She had been home from her own marriage for about a year and a half. She had retained a lawyer in September 1986. The divorce decree would not come until October 1987. She was in the middle of her own salvage. She had no business taking on someone else's." },
        { kind: "plain", text: "She took it on anyway." },
      ],
    },
    {
      type: "artifactCard",
      label: "Artifact · September 5, 1986",
      heading: "The Lawyer's Fee Agreement",
      imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811219/buyahka-abrar/drive-docs/15w5XTsDZ0uQAEtS38cjxnp98zLAO1OTw.png",
      alt: "Goldsmith Law Firm fee agreement, retained by Hina, September 5, 1986",
      caption: "The retainer Hina signed at the Goldsmith Law Firm to begin the proceedings that would end her first marriage. September 5, 1986. She was nineteen. The decree itself would not come until October 1, 1987. In the spring between those two dates, the boy turned up with a duffel bag and she made room for him.",
    },
    {
      type: "prose",
      lines: [
        { kind: "plain", text: "What that looked like was not romantic in the way a movie would film it. She was not my caretaker. She was not my servant. She was not someone trying to fix me. What she gave me was harder than any of that to describe — she gave me her company. Sometimes we sat in silence and that was enough. Sometimes we ate something together and one of us picked up the check, and when I could pick it up I did, and we did not fight over it. We did what people who care about each other do, by the ethics and etiquettes that had been put into both of us. She was not, in 1987, my girlfriend. We were not engaged. We were not anything that needed a name. She was a young woman who had been broken open and put back together by her own three years in another state, and she looked at a fifteen-year-old boy and decided that whatever shape this would take, he would not have to sit by himself." },
        { kind: "plain", text: "I did not understand at the time what she was doing. I understand now." },
        { kind: "plain", text: "She was a teenager and the only adult in my life." },
        { kind: "plain", text: "I have written that sentence in this book before. I will write it again before the book is done. It is the load-bearing sentence of how I read her, and how I read myself, and how I read the marriage we eventually built. She was a teenager and the only adult in my life. The men this chapter has gathered — Ikram, Khalid Beg, Masoom Jaleel, Uncle Nader, Uncle Hameedudin, Uncle Bajwa, Mr. Wilbur — built the masjid. The masjid produced the entryway. The entryway produced the meeting. And six years after the meeting, when the boy fell out of the world the men had built, the young woman who had walked through that entryway in 1981 caught him." },
        { kind: "plain", text: "You will hear me say, later in this book, that Hina and I built each other. That neither of us was the hero. That goodness, decency, faith, love — these are not rankable, and a marriage is not a transaction. All of that is true." },
        { kind: "plain", text: "And it is also true that she went first." },
        { kind: "plain", text: "Before there was a marriage between us, before there was a child, before there was a flower shop with our names on it, before there was anything either of us could call a future — she gave me her company. She gave me her time. She gave me the dignity of being treated like a person, not a project. The shade I would later give her was structural. She was a woman, and I was a man in a world that listened differently to men. I do not take credit for what the world handed me to hand to her. The shade she gave me was something else. It was hers. She had been broken in ways I did not yet understand, and out of what little she had managed to put back together, she made room." },
        { kind: "plain", text: "That is one of the four ways she saved me. There are three others, and they will come in their own chapters. But this is the one Chapter 3 has to carry, because Chapter 3 is the chapter where the inheritance the men built becomes the place inside which a particular boy fell, and Chapter 3 has no honest ending without saying the name of the person who caught him." },
      ],
    },
    {
      type: "asideCard",
      label: "A version not mine · in my sister's own framing",
      heading: "What my sister would say",
      paragraphs: [
        "My sister's version and recollection of events would taint towards my mother, and reflect much of her mindset and personality. The narrative is along these lines: my parents were dead against the marriage; I would not listen and was smitten by Hina; Hina was a type of vixen and seductress, taking advantage of an underage kid; my parents repeatedly summoned me home, but I would not return because I had found shelter and comfort in Hina; the two of us were having our cakes and eating them as well.",
        "It is a neatly packaged and perfectly sensible narrative. How or who can argue such a narrative — it is all self-evident and clear. In all of this of course the Koshul family is and was a beacon of light, of hope, of goodness and all the rest. There existed just a couple of black sheep. And black marks on the family which would be Hina and Abrar.",
        "This topic has never been spoken upon between my sister and I. From 1987 until January 2024. Never once has it been spoken about. This reflects our personalities, or at least in part each of our personalities.",
        "I by no means was an angel, have been an angel, am without deficiencies. But things along the lines of drugs, robberies, alcohol, casual sex, shirk, blatant lying, slandering of others — these I do not recall egregiously. As for Hina being a vixen: please. She was and is a simple, beautiful, pure soul who was caught in a dirty, nasty world with all its games, hustles and traps. The woman was a sweetheart of a woman. In truth, one this world and community and her own family did not deserve.",
        "After God, who would know her better than I. But there is a possibility that I am a blatant liar and have fights I need to finish or win. Perhaps that possibility remains.",
      ],
    },
    {
      type: "prose",
      lines: [
        { kind: "plain", text: "I tell you all of this because the rest of the book happens in the shadow of what I have just named. The masjid that my father and Dr. Beg and Masoom Jaleel and the other families had built — the masjid named after its limitation, the masjid that split and went to court and was lost in court and was rebuilt anyway, the masjid with the Black American convert's sign on the fence — that masjid produced the entryway. The entryway produced the meeting. The meeting, six years later, produced the rescue. The rescue, two years after that, produced the wedding the boy actually attended." },
        { kind: "plain", text: "I did not lay the brick. I did not write the check. I did not testify in court. I did not catch myself when I fell. I was the boy in the entryway, already, without knowing it, in the right place. The men I have named in this chapter built the masjid. The masjid built me. And in the entryway, in a blue kameez and a long overcoat in 1981, was the woman who would build the rest." },
        { kind: "plain", text: "I owe them all. I owe the men I named. I owe the men I did not name. I owe the wives in the kitchens whose names I am still learning. I owe Hina most of all. The book that follows is, in its own slow way, the receipt." },
      ],
    },
    {
      type: "artifactRow",
      rowLabel: "The Papers",
      heading: "What survived in writing",
      items: [
        {
          imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811301/buyahka-abrar/drive-docs/1U_3HKx9izk3EUhIB_roDQIy_41xkTeS9.png",
          alt: "Beg Family Tree, page 1, extended generations",
          caption: "Beg Family Tree, part 1. Khalid Beg's siblings: Zahid, Maroof, Khalida, Shahida, Abida, Aisha. Nusrat's tier: Rashida, Wahida, Nusrat, Ahmed, Nizamu, Masud, Nisa, Zenith. In Hina's hand.",
        },
        {
          imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811221/buyahka-abrar/drive-docs/17GHKqhzGgXocP-9c5LG6G8U0hX8o7uJH.png",
          alt: "Beg Family Tree, intermediate page",
          caption: "Beg Family Tree, intermediate page. The note at bottom: \"My father's grandfather was my mother's great grandfather — both on their fathers side.\" Khalid Beg and Nusrat Beg were second cousins. The Beg family lived in Lahore before Multan, pre-partition.",
        },
        {
          imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811307/buyahka-abrar/drive-docs/1WB3mccy7CzemSFbaOAPkz7w3PRB6xd48.png",
          alt: "Yasin Certificate, certified marriage record copy, September 4, 1986",
          caption: "Township of Teaneck certified copy of the marriage record. Issued September 4, 1986 — one day before Hina retained the divorce attorney. The bridge document.",
        },
        {
          imageSrc: "https://res.cloudinary.com/kh0ahdrd/image/upload/v1789811233/buyahka-abrar/drive-docs/1bh9T2ZUi1pe_sv8mRDtztd34jivxVebV.png",
          alt: "Goldsmith Law Firm fee agreement, page 2",
          caption: "Page 2 of the fee agreement. Handwritten note in the margin about annulment. The lawyer was open to the case being either divorce or annulment.",
        },
      ],
    },
    { type: "chapterEnd", nextTitle: "Chapter Four — November 10, 1989: Love Forged in Fire" },
    {
      type: "fpImage",
      eyebrow: "KHALID BEG AND AUNTIE BEG",
      image: { publicId: "buyahka-abrar/chapter-03/01_image", resourceType: "image" },
      alt: "The two named carriers, seated together. The Beg parents.",
      caption: "The two named carriers, seated together. The Beg parents — both anchors of the theology this book carries.",
    },
  ],
};

export default chapter03;
